### ISSUE TITLE
(Bug): No Dislike Count Shown

### ISSUE THREAD

**Issue by CurtisTD** [Anarios/return-youtube-dislike#249] opened 2021-12-08 22:55 UTC
### Browser

FireFox

### Browser Version

FireFox 94

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 1.1.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=vC5JnJD9KzY

### What happened?

A bug happened!

I installed the extension today for the first time. I have tried seeing any dislikes on any video, and it just defaults to the new 'DISLIKE' count.

Happens on any video, can't seem to find any that work.

**Comment by Makeineer** [comment] 2021-12-08 23:12
Can confirm this one. Seems to resonate specifically with timestamped videos on my end.

**Comment by krystian3w** [comment] 2021-12-09 01:35
See too #244

**Comment by DARKDRAGON532** [comment] 2021-12-10 06:56
Is this still happening?

**Comment by krystian3w** [comment] 2021-12-10 07:51
Maybe server side bug (I unable reproduce on Windows 7 with FF95).

**Comment by DARKDRAGON532** [comment] 2021-12-10 07:55
There was an API outage near the time this issue was opened, might be due to that.

**Comment by Anarios** [comment] 2021-12-14 01:01
Should be fixed now, feel free to reopen if still happens

**Closed by Anarios** 2021-12-14 01:01 UTC
Labels: bug
