### ISSUE TITLE
Doesn't show youtube dislike amount anymore

### ISSUE THREAD

**Issue by ShcemX** [Anarios/return-youtube-dislike#797] opened 2022-10-30 03:24 UTC
### Browser

Google Chrome

### Browser Version

Version 93.0.4577.107

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 3.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=2vA_rlm9Fqc

### What happened?

I watch any Youtube video and one of them show the dislike amount.

### How to reproduce/recreate?

Watch any Youtube video.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by sainishwanth** [comment] 2022-10-30 08:31
Just to add onto this, Uberscript (on safari) doesn't work either.

**Comment by SprinkleBunn** [comment] 2022-10-30 14:07
It also does not work on Opera GX currently.

**Comment by Moondarker** [comment] 2022-10-31 00:03
Are you sure you're using the extension? Version 3.0.1 sounds a lot like userscript.
If that's the case, it's likely a duplicate of #748 and you can take a look at proposed solutions [here](https://github.com/Anarios/return-youtube-dislike/issues/795#issuecomment-1294906772)

**Comment by rugabunda** [comment] 2022-10-31 01:00
Likes and dislikes are being phased out. Seems to be rolling blackouts, inconsistent... some channels have it some do not.

![image](https://user-images.githubusercontent.com/38260267/198911244-30880452-4360-4ed3-9fce-52b4eb6d271e.png)

**Comment by Scott16546** [comment] 2022-10-31 01:05
![Screenshot 2022-10-30 at 18 02 28](https://user-images.githubusercontent.com/82477557/198911763-c62dc9a3-e8ae-4a1c-8a08-87522864e415.jpg)
Its still working.

**Comment by rugabunda** [comment] 2022-10-31 01:21
This is my channel, it is not working. I never disabled likes or dislikes. 

![image](https://user-images.githubusercontent.com/38260267/198912946-02db207e-756f-46d3-9ae6-87042d5f13a2.png)

**Comment by vadimTovstik** [comment] 2022-10-31 16:29
It doesn't work more. Any news?

![image](https://user-images.githubusercontent.com/39420126/199059480-901c5713-21cc-4210-ac0b-d19f724c17d4.png)

**Comment by ronny941** [comment] 2022-11-23 23:39
> This is my channel, it is not working in this circumstance. I never disabled likes or dislikes.
> 
> ![image](https://user-images.githubusercontent.com/38260267/198912946-02db207e-756f-46d3-9ae6-87042d5f13a2.png)

same problem for me but on firefox 
on chrome edge and brave it works perfectly

**Comment by vadimTovstik** [comment] 2022-11-23 23:42
> > This is my channel, it is not working in this circumstance. I never disabled likes or dislikes.
> > ![image](https://user-images.githubusercontent.com/38260267/198912946-02db207e-756f-46d3-9ae6-87042d5f13a2.png)
> 
> same problem for me but on firefox it give the first screen and the second with like numbers not displayed correctly and dislike with nothing showed on chrome edge and brave it works perfectly

It's SaveFrom conflict. Need to ask owner to fix this. This thread, please text your problem there too to up this thread https://github.com/Anarios/return-youtube-dislike/issues/769

**Comment by ronny941** [comment] 2022-11-23 23:46
yeah i have disabled and it working
i hope they updated the extension

**Comment by VetaLioSTV** [comment] 2022-11-24 23:06
> > > This is my channel, it is not working in this circumstance. I never disabled likes or dislikes.
> > > ![image](https://user-images.githubusercontent.com/38260267/198912946-02db207e-756f-46d3-9ae6-87042d5f13a2.png)
> > 
> > 
> > same problem for me but on firefox it give the first screen and the second with like numbers not displayed correctly and dislike with nothing showed on chrome edge and brave it works perfectly
> 
> It's SaveFrom conflict. Need to ask owner to fix this. This thread, please text your problem there too to up this thread #769

I had the same problem! When you click like/dislike, it dissapears and changes with "Disabled by owner" \ "icon thumb down".
As you mentioned about "SaveFrom", i had also [Y2mate](https://y2mate.tools/en57g1) extensions, which caused that's unexpected behaviour. So i disabled it and it works as it should.

PS Also, why github link in TamperMonkey redirects to [fork ](https://github.com/hyperstown/return-youtube-dislike)and not main(this) repo?
![image](https://user-images.githubusercontent.com/15155286/203872623-8923f1b3-2bed-4497-89a8-09b7c83b0c58.png)

**Comment by vadimTovstik** [comment] 2022-11-24 23:08
Please dublicate your posts here to up this thread. SaveFrom conflict https://github.com/Anarios/return-youtube-dislike/issues/769

**Comment by ErykDarnowski** [comment] 2022-11-26 01:10
This issue should be closed, it's a duplicate of #769.

**Closed** 2023-01-25 22:02 UTC
Labels: bug
