### ISSUE TITLE
(Bug): Flashes real dislike number for few frames and then resets to 0

### ISSUE THREAD

**Issue by LordSyriusz** [Anarios/return-youtube-dislike#156] opened 2021-12-02 21:24 UTC
### Browser

Opera GX

### Browser Version

LVL3 (core: 81.0.4196.61)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.0.0.2

### Video link where you see the problem

https://www.youtube.com/watch?v=2lAe1cqCOXo

### What happened?

After loading a video, I can see dislike number (for rewind I see 9.5M dislikes) for few frames and then it resets to 0. 
What I fear is happening, the youtube has a script that searches for dislike field and automatically resets it to 0. Or maybe extension just doesn't like Opera. But even if they don't do it yet, they will at some point.
So, one solution would be to randomise the name of a field? But I would also add a counter directly into extension, so no script on the site can tamper with it.

**Comment by SnGmng** [comment] 2021-12-02 21:48
same problem here (Extension version: 1.0.0.2, Opera version: 81.0.4196.60)

**Comment by mphelp** [comment] 2021-12-02 22:18
I think I understand the root cause.
@SnGmng is right. When youtube returns null, the dislike count gets set to 0 instead of what's in the api. Looking into this some more
<img width="424" alt="Screen Shot 2021-12-02 at 4 15 43 PM" src="https://user-images.githubusercontent.com/25730130/144512234-256f1cf7-1cfc-45a7-b2e9-352fd49bbe15.png">

**Comment by mphelp** [comment] 2021-12-02 22:53
@SnGmng I can't find that video anymore

**Comment by SnGmng** [comment] 2021-12-02 23:04
@mphelp The video id doesnt matter, the bug is litteraly on EVERY video.

It deesnt even work on the youtube rewind video: https://www.youtube.com/watch?v=YbJOTdZBX1g
```
[return youtube dislike]: response from api:
[return youtube dislike]: {"id":"YbJOTdZBX1g","dateCreated":"2021-12-01T12:03:27.394366Z","likes":3066540,"dislikes":19901183,"rating":1.534060777378759,"viewCount":222359160}
[return youtube dislike]: response from youtube:
[return youtube dislike]: {"likes":3067027,"dislikes":null,"viewCount":222446990}
```

**Comment by mphelp** [comment] 2021-12-02 23:07
@SnGmng I'm using opera and this is what I get
```
[return youtube dislike]: response from api:
[return youtube dislike]: {"id":"YbJOTdZBX1g","dateCreated":"2021-12-01T12:03:27.394366Z","likes":3066540,"dislikes":19901183,"rating":1.534060777378759,"viewCount":222359160}
[return youtube dislike]: response from youtube:
[return youtube dislike]: {"likes":3067027,"dislikes":19908300,"rating":1.5339688,"viewCount":222447220}
```

**Comment by mphelp** [comment] 2021-12-02 23:08
@SnGmng can you send me the page source of your rewind 2018 video?

**Comment by SnGmng** [comment] 2021-12-02 23:38
@mphelp I have no averageRating in the page source

**Comment by mphelp** [comment] 2021-12-02 23:41
@SnGmng super weird! I can see it
<img width="678" alt="Screen Shot 2021-12-02 at 5 41 06 PM" src="https://user-images.githubusercontent.com/25730130/144520237-a3b71a39-5b10-4ca2-94ce-ad0aa577feb9.png">

**Comment by RMoDOOM** [comment] 2021-12-03 00:17
I'm seeing the same "null" for the "response from youtube" item, even on Rewind 2018 now. Is it possible youtube got wise to this extension and stealth-updated the API?

**Comment by quarma** [comment] 2021-12-03 00:54
Having the same issue on Google Chrome 96.0.4664.45 but I believe the issue is tied to Sponserblock since turning off that extension causes the dislikes to be viewed properly.

**Comment by Anarios** [comment] 2021-12-03 01:04
Fixed in 1.1.0.0 (released to FF, in approval for chrome, should be up tommorow)

**Closed by Anarios** 2021-12-03 01:04 UTC
Labels: bug

**Comment by mphelp** [comment] 2021-12-03 01:06
@RMoDOOM If so, shame on youtube for going back on their word. But good on us for scaring them

**Comment by LordSyriusz** [comment] 2021-12-03 18:27
It works now! Thanks!
