### ISSUE TITLE
return youtube comment dislikes

### ISSUE THREAD

**Issue by NorthernChicken** [Anarios/return-youtube-dislike#1024] opened 2023-12-31 04:05 UTC
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Not sure how possible this is or if it is in scope, but it would be nice to see the number of dislikes on comments.

### Can you work on this?

- [ ] Yes
- [X] No

### Will you be available for follow-up questions to help developers implement this?

Yes

**Comment by EricE549X** [comment] 2023-12-31 16:29
how would that work retroactively tho? as far as i'm aware, there was never an API for comment dislikes specifically

**Comment by NorthernChicken** [comment] 2023-12-31 21:41
But this program doesn't utilize the youtube api, right? Would the api be needed?

**Comment by Nadeem2007** [comment] 2024-01-01 15:56
Even I also need this feature

**Comment by Nightcaat** [comment] 2024-01-23 01:51
This is a duplicate of multiple issues. That and I believe this idea has already been turned down in the past for the reason mentioned above: it would make for an enormous database with very limited usefulness.

It would be kinda cool but this is out of scope for RYD.

**Closed by Nightcaat** 2024-01-23 01:51 UTC
Labels: enhancement
