### ISSUE TITLE
(Bug): Dislike qty doubles at livestreams

### ISSUE THREAD

**Issue by Kuntsaito** [Anarios/return-youtube-dislike#125] opened 2021-11-30 19:45 UTC
### Browser

Firefox Official Build

### Browser Version

94.0.2 64-bit

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.0.0.0

### Video link where you see the problem

https://www.youtube.com/watch?v=vw7EIjEtjmU

### What happened?

![3003](https://user-images.githubusercontent.com/60572698/144116453-b3838331-11b8-42b4-a37c-01495d9767c5.PNG)

**Comment by niwla23** [comment] 2021-11-30 19:55
![image](https://user-images.githubusercontent.com/46248939/144118354-e3413357-6ab4-49a9-852b-a5e192da6e4b.png)
looks fine on my machine :thinking:

**Comment by Kuntsaito** [comment] 2021-11-30 23:47
Possible steps to reproduce
1) Log in yt account where dislikes is still visible
2) Run stream that isnt viewed by extension user before ? (in other words: maybe not listed in like/dislike database?)
Not sure why this sometime happens. But happens mostly every time on new streams, just after you start to watch it.

**Comment by hisamafahri** [comment] 2021-12-01 02:00
> Log in yt account where dislikes is still visible

What do you mean by this? @Kuntsaito

**Comment by DARKDRAGON532** [comment] 2021-12-01 02:25
> 1. Log in yt account where dislikes is still visible

If you can already see dislikes, the dislike count might double, this is a known issue.

**Comment by milesdamore** [comment] 2021-12-01 06:20
The issue is often caused when likes are also hidden I believe.

**Comment by laughingsheep** [comment] 2021-12-01 16:40
What is the point of using this if you can still dislikes?

**Comment by Kuntsaito** [comment] 2021-12-01 23:27
> What is the point of using this if you can still see dislikes?

Because i have few youtube accounts, and in some of them dislikes already removed.

**Comment by cyrildtm** [comment] 2022-01-08 02:22
Is this still happening? possible duplicate of #86

**Closed** 2022-01-10 19:56 UTC
Labels: bug
