### ISSUE TITLE
(Feature Request): Live disliking

### ISSUE THREAD

**Issue by Cortex128** [Anarios/return-youtube-dislike#93] opened 2021-11-30 00:58 UTC
### Extension or Userscript?

Both

### Request or suggest a new feature!

Someone has probably suggested this already but I'll ask anyway. Make it so you can hit the dislike button and the number actually increases, instead of it just being whatever the count was when YT disabled dislikes. This will probably mainly be important when google removes dislikes from the API entirely.

### Ways to implement this!

See above

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by DARKDRAGON532** [comment] 2021-11-30 03:41
Duplicate of #59

**Comment by laughingsheep** [comment] 2021-12-01 16:52
@Anarios Can you please close this?

**Closed** 2021-12-03 01:10 UTC
Labels: enhancement
