### ISSUE TITLE
Wild Suggestion (Suggestion)

### ISSUE THREAD

**Issue by Decapitater** [Anarios/return-youtube-dislike#21] opened 2021-11-20 15:10 UTC
Is it possible to Add a machine learning api that would see YouTube comments and further help in refining things 
@Anarios 
(I am ready to help in production , hit me up)

**Comment by Anarios** [comment] 2021-11-20 20:19
Hmmm, not sure. I see videos with 100k views, 1000 likes and 20 dislikes. And video with 100k views, 1000 likes and 2000 dislikes - doesn't look like it's predictable at all :( Would be really nice though.

**Comment by Decapitater** [comment] 2021-11-20 20:35
Well if for nothing it could help strengthen the basis. When youtube removes it from the api , it can help to get a somewhat rough figure with the comments or for things people do like (like this comment to dislike this video or use this comment as dislike)

If interested ,  i am more than ready to help

**Comment by Decapitater** [comment] 2021-11-20 20:37
> Hmmm, not sure. I see videos with 100k views, 1000 likes and 20 dislikes. And video with 100k views, 1000 likes and 2000 dislikes - doesn't look like it's predictable at all :( Would be really nice though.

I meant using machine learning api to further strengthen the basis of the external data  when the api removes support

**Comment by felipe005** [comment] 2021-11-22 08:04
Or you guys could store the video id along with the deslike count that people give to that video in your extension

**Comment by Felix14-v2** [comment] 2021-11-23 16:20
Channel authors can still get information about dislikes in their videos through the creative studio. Is it possible to add the ability for channel authors to provide this information to users with an extension to generally make information about the number of dislikes on their channel more accurate?

**Comment by Anarios** [comment] 2021-11-23 16:39
> Channel authors can still get information about dislikes in their videos through the creative studio. Is it possible to add the ability for channel authors to provide this information to users with an extension to generally make information about the number of dislikes on their channel more accurate?

yes, it's planned

**Comment by Decapitater** [comment] 2021-12-03 03:26
@Anarios is there a way to help the cause ?

**Comment by aidanhasaknife** [comment] 2021-12-17 07:40
i'm led to believe that this idea, as it adds an entirely new paradigm to the project, should be put on the far back-burner for now. is it even within the current scope of the project, given that a ML model would only _predict_ what the dislike count would be?

**Comment by Decapitater** [comment] 2021-12-17 13:37
Hmm right , 
any help needed in development ? @Anarios

**Comment by Anarios** [comment] 2021-12-19 00:33
@Decapitater, not that I can think of.

**Comment by Anarios** [comment] 2021-12-19 00:34
Duplicate of #99, so closing this one, we can continue there

**Closed by Anarios** 2021-12-19 00:34 UTC
