### ISSUE TITLE
Formula for extrapolating dislike count is incorrect!

### ISSUE THREAD

**Issue by HansBrende** [Anarios/return-youtube-dislike#756] opened 2022-09-14 20:12 UTC
### What happened?

When I navigate to your [FAQ](https://github.com/Anarios/return-youtube-dislike/blob/main/Docs/FAQ.md#5-how-is-the-dislike-count-calculated), it displays the following formula for calculating dislike count:

  $$ \textup{RYD Dislike Count} = \left( \frac{\textup{RYD Users Like Count}}{\textup{RYD Users Dislike Count}} \right) \times \textup{Public Like Count} $$
  
  
This is mathematically incorrect. Your numerator & denominator are switched. The correct formula should be:

  $$ \textup{RYD Dislike Count} = \left( \frac{\textup{RYD Users Dislike Count}}{\textup{RYD Users Like Count}} \right) \times \textup{Public Like Count} $$
  
**I hope this is simply a typo and not how you are actually calculating the extrapolated number of downvotes!**

### How to reproduce/recreate?

Look at [FAQ section on calculating downvotes](https://github.com/Anarios/return-youtube-dislike/blob/main/Docs/FAQ.md#5-how-is-the-dislike-count-calculated).

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by emelrad12** [comment] 2022-09-15 08:45
Most likely a typo on the FAQ, as that should make all dislike counts over 100% of the likes, which is not the case.

**Comment by Nightcaat** [comment] 2023-10-24 03:27
As mentioned, duplicate of #725, fixed in #726

**Closed by Nightcaat** 2023-10-24 03:27 UTC
Labels: bug, duplicate
