### ISSUE TITLE
Undoing dislike does not change number on screen

### ISSUE THREAD

**Issue by FernandoSapient** [Anarios/return-youtube-dislike#190] opened 2021-12-04 16:46 UTC
This is probably a minor, cosmetic bug that hasn't been reported yet, but I've found that if I dislike a video, then change my mind and click the dislike button again to undo disliking it, the number doesn't update.

Specifically, let's say the video has 100 dislikes. I click the dislike button, it is now filled and the number of dislikes is incremented to 101. I click the button again, the button is no longer filled, but the number doesn't change from 101. If i click the button a third time, the button is filled again and the number is incremented to 102. This gives the (I'm hoping) false impression that you are adding multiple dislikes to a video/database

This is particularly scary to the user if you've decided that you actually "like" it (let's say you dislike because of something said at the start of the video but when you watch it all the way through you realize it's actually good)

**Comment by Nightcaat** [comment] 2021-12-04 16:52
I think this might be a duplicate of #174

**Comment by FernandoSapient** [comment] 2021-12-04 17:09
It's very similar, but #174 is about clicking the like button once the dislike is selected. I'm pointing out that the problem happens even if you click the dislike button again _without_ clicking the like button (i.e. you click dislike on the video, then decide "actually, I'm neutral on it" and click dislike again to unmark it)

Additionally, I'm adding the concern of whether the "multiple dislikes per person" get added to the database

Hopefully they have the same cause and addressing #174 will address this, but I don't really have time to check the code right now

**Comment by Nightcaat** [comment] 2021-12-04 17:31
I can’t recreate this on version 1.1.0.2 of the Firefox extension, what are you using?

The database currently caches results from the YouTube API since public dislike data won’t be removed until December 13th, so there’s no issue of multiple dislikes per person

**Comment by FernandoSapient** [comment] 2021-12-04 18:09
version 1.1.0.0 on chrome

**Comment by DARKDRAGON532** [comment] 2021-12-04 18:43
The dislikes aren't being sent to the database yet, and this is just for UX. Will be fixed though

**Comment by Frontesque** [comment] 2021-12-04 20:18
I'll look into this. I had tested it and thought it was working.

**Comment by Frontesque** [comment] 2021-12-04 20:46
I can't seem to replicate this bug. Is anyone else having this issue?

**Comment by Nightcaat** [comment] 2021-12-04 21:08
> version 1.1.0.0 on chrome
I can’t reproduce this either

**Comment by Frontesque** [comment] 2021-12-04 22:17
This might be an issue with your browser cache. Try clearing that or using a new browser profile. This definitely isn't an issue with the extension.

**Closed by Frontesque** 2021-12-04 22:17 UTC
