### ISSUE TITLE
Dislikes still not showing up in the latest version of the extension (issue with rolling like count)

### ISSUE THREAD

**Issue by GemplelyTivadar** [Anarios/return-youtube-dislike#950] opened 2023-10-13 21:36 UTC
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

118

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.11

### Video link where you see the problem

Happens on every video

### What happened?

I still can't see the dislike counter. My account got selected for an a/b testing feature for "rolling like count", where the like counter updates in real time. I think that's the reason why the extension still doesn't work for me, because if I switch to an account that doesn't have the rolling likes experiment, or open a private window, then the extension works again.
![dislikes](https://github.com/Anarios/return-youtube-dislike/assets/95102462/aa1c32f1-0a52-4f69-bf11-345024f2cf4e)

### How to reproduce/recreate?

Open any video with an account that has the rolling like count experiment enabled.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by raspin0** [comment] 2023-10-13 21:39
Have you tried to find similar open issues?
Apparently, **not** 

This looks like a duplicate of https://github.com/Anarios/return-youtube-dislike/issues/944

**Comment by tazlsucks** [comment] 2023-10-13 21:43
This is not a duplicate, this person seems to have a different bug with the updated version of the extension.

**Comment by GemplelyTivadar** [comment] 2023-10-13 21:44
The issue you linked does not mention the rolling likes experiment, also it is for the previous version of the extension (v3.0.0.10).
I opened this issue for the latest version (v3.0.0.11).

**Comment by tazlsucks** [comment] 2023-10-13 21:47
@GemplelyTivadar Try using an incognito tab with the extension, make sure it doesn't have something to do with Firefox, and instead the rolling likes experiment like you said.

**Comment by tdreams2** [comment] 2023-10-14 06:51
I found a solution and the dislike count appears but I'm not sure if it's reliable this way or not

I changed this line of code in createDislikeTextContainer() function:
`const textNodeClone = (getLikeButton().querySelector("button > div[class*='cbox']") || getLikeButton().querySelector('div > span[role="text"]').parentNode).cloneNode(true);`

changed to this:
`const textNodeClone = (getLikeButton() || getLikeButton().parentNode).cloneNode(true);`

**Comment by Anarios** [comment] 2023-10-14 11:09
Looks like you're receiving an even different UI version (i.e. an experimental A-B testing YouTube UI).

**Comment by Anarios** [comment] 2023-10-14 11:13
Closing as clone of #946

**Closed by Anarios** 2023-10-14 11:13 UTC
Labels: bug
