### ISSUE TITLE
(Bug): "DISLIKE DISABLED" on new Videos

### ISSUE THREAD

**Issue by agent-LuluDodo** [Anarios/return-youtube-dislike#472] opened 2022-02-03 19:42 UTC
### Browser

Firefox

### Browser Version

Firefox 97

### Extension or Userscript?

Extension

### Extension/Userscript Version

v2.1.0.3

### Video link where you see the problem

The Video needs to be under 5 min old

### What happened?

On Videos which are new, the Dislike count shows as "Dislikes Disabled".
Shouldn't that be more like "Dislikes calculating", "Not enough info" or "Dislike Unknown" _(with a tooltip aside explaining possible reasons)[credits for this one: @cyrildtm]_?

![Dislike Disabled](https://user-images.githubusercontent.com/98981925/152416856-14901f9d-a083-4158-b0ef-8704a82b9170.png)

**Comment by cyrildtm** [comment] 2022-02-03 21:42
possible duplicate of #461
Please see if your problem resolves by itself in a while

**Comment by cyrildtm** [comment] 2022-02-03 21:45
possible duplicate of #444 
Please see if your problem resolves by itself if you like the video once (and refresh) or wait for a while

**Comment by andry81** [comment] 2022-02-19 11:52
I know the video from 2022.01.31 and it still has it disabled. I think it is not about when it has published.

**Comment by sy-b** [comment] 2022-02-19 14:30
"Dislike Disabled" means that the creator has disabled both likes & dislikes.

The extension uses the number of likes to extrapolate the dislikes count.

Without like count it can't extrapolate

**Comment by agent-LuluDodo** [comment] 2022-02-19 18:39
> "Dislike Disabled" means that the creator has disabled both likes & dislikes.
I'm the creator of this Video and I have likes and dislike enabled.

I understand that there is not enough info to display the dislike count, but I think the message "Dislike Disabled" is misleading. It should be more like "Dislikes calculating" or "Not enough info"

**Comment by agent-LuluDodo** [comment] 2022-02-19 18:42
> I know the video from 2022.01.31 and it still has it disabled.

Send the Link!

**Comment by agent-LuluDodo** [comment] 2022-02-19 18:43
> possible duplicate of #444 Please see if your problem resolves by itself if you like the video once (and refresh) or wait for a while

Yes, it does show up after a while. But the Bug report is to show that this is misleading. It should be something like "Dislikes calculating" or "Not enough info".

**Comment by cyrildtm** [comment] 2022-02-19 19:22
What about saying "Dislike Unknown" and put a tooltip aside explaining possible reasons

**Comment by agent-LuluDodo** [comment] 2022-02-19 21:23
> What about saying "Dislike Unknown" and put a tooltip aside explaining possible reasons

That sounds better than mine. Adding this as a possibility in the Description.

**Comment by andry81** [comment] 2022-02-19 21:42
> > I know the video from 2022.01.31 and it still has it disabled.
> 
> Send the Link!

I think it those videos where both likes and dislikes are disabled.

**Comment by agent-LuluDodo** [comment] 2022-02-20 00:04
> I think it those videos where both likes and dislikes are disabled.

Ah, ok. Still thx

**Comment by CreaZyp154** [comment] 2022-04-07 06:54
Should we really say "DISLIKE DISABLED" when like/dislike count is disabled by owner ? It shows "LIKE" instead of the like counter, indicating that the owner disabled it.

Also for new videos since this is a new video I don't think it would be an issue showing 0 dislikes (it's probably really close anyways)

**Comment by cyrildtm** [comment] 2022-04-07 07:12
@CreaZyp154 Yeah that's why I was asking you to take a look. Do you know if we have ways to tell the reason we don't have the numbers? So we can properly reflect it. Personally I prefer "dislike unknown" but it could be more specific if we know what has happned

**Comment by CreaZyp154** [comment] 2022-04-07 08:46
At [line 151 in `src/state.js`](https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/combined/src/state.js#L151) you can see that it shows "DISLIKES DISABLED" when the API returns both 0 likes, 0 disikes and 0 views, which is a weird way to tell if like/dislike count is disabled... Not only does it wrongly shows that on new videos, but it also shows dislike count on video where the like/dislike count IS disabled...

I think the easiest way to find that is by testing if the LIKES field contains a number or not.

As for errors; in my PR it shows "TEMPORARILY UNAVAILABLE" for when the API returns an error (4xx and 5xx) and when other networking issues occurs. I don't think it is necessary to have another text.

**Comment by cyrildtm** [comment] 2022-04-07 13:11
I see. At least we can tell apart API server errors from zero counts. 
* like >0 dislike >0
* like >0 dislike =0
* like =0 dislike =0
* like =0 dislike >0


Your PR is good!

**Comment by CreaZyp154** [comment] 2022-04-07 13:24
@cyrildtm Should I fix this issue in the PR ? Or make a new one ?

**Comment by cyrildtm** [comment] 2022-04-07 13:59
I don't know :D You are the expert. 
If this can be fixed systematically then I would go for one PR, otherwise I would fix different things separately. 
To me it looks like it's worth giving a more high-level summary and see if we can catch all/most of the exceptional cases. Like making a table of all possible outcomes, which covers all combinations of variables. If it's not possible I'm also fine with it; reporting server error more specifically is already one step forward.

**Comment by CreaZyp154** [comment] 2022-04-07 14:02
Yeah, you're right... the PR is indirectly but still related to this so yeah I'll update it.

**Closed** 2022-04-26 16:30 UTC
Labels: bug
