### ISSUE TITLE
(Bug): NaN instead of dislikes count

### ISSUE THREAD

**Issue by ivanosh** [Anarios/return-youtube-dislike#296] opened 2021-12-14 01:27 UTC
### Browser

Safari

### Browser Version

15.1

### Extension or Userscript?

Userscript

### Extension/Userscript Version

0.6.1

### Video link where you see the problem

https://www.youtube.com/watch?v=Hvw2cNQUuUc

### What happened?

NaN shows after page loaded

https://user-images.githubusercontent.com/5702943/145915706-5a99997d-0088-4496-b907-e2aefba55f8d.mov

Here is how it looks on page refresh

**Comment by PacketOperator** [comment] 2021-12-14 01:35
I just noticed this as well.  The amount of dislikes, for me, is shown for a sec as the page finishes loading, it turns into NAN.

**Comment by l00po** [comment] 2021-12-14 01:35
Same on FF 95

**Comment by TiagoTiago** [comment] 2021-12-14 01:37
Another confirmation on Firefox 95.0

**Comment by mbmigone** [comment] 2021-12-14 01:37
Same on FF 94.0.2

**Comment by EleKtr1X** [comment] 2021-12-14 01:40
same for me on firefox 95.0 with the addon

**Comment by xenanthropy** [comment] 2021-12-14 01:48
Had the same problem (Firefox 95, Linux, extension) but re-installing the extension fixes the issue for me!

**Comment by mbmigone** [comment] 2021-12-14 01:50
Same on FF 94.0.2

> Had the same problem (Firefox 95, Linux, extension) but re-installing the extension fixes the issue for me!

This did the trick. Thanks!

**Comment by De96UtopiaLife341** [comment] 2021-12-14 01:50
I think Google might've shut down the API. Found something right here. https://www.newsweek.com/return-youtube-dislike-browser-extension-google-chrome-firefox-1654339

**Comment by De96UtopiaLife341** [comment] 2021-12-14 01:50
![Screenshot_20211213_205026](https://user-images.githubusercontent.com/79053290/145918230-2066d7fe-b4c4-40bb-ae90-4925bfcd5a0a.png)

**Comment by Anarios** [comment] 2021-12-14 01:52
The api was shut down for 12 hours now. Extension works fine - userscript will be fixed as well.

**Comment by De96UtopiaLife341** [comment] 2021-12-14 01:54
> The api was shut down for 12 hours now. Extension works fine - userscript will be fixed as well.

Ok. Thanks!

**Comment by jtbx** [comment] 2021-12-14 02:33
Same problem.
I'm gonna reinstall.

**Comment by jtbx** [comment] 2021-12-14 02:33
Fixed.

**Comment by MagentaPuppy** [comment] 2021-12-14 02:53
i had the problem, fixed with re-install

**Comment by alexmehta** [comment] 2021-12-14 03:14
confirmation on FF dev edition

**Comment by VirtualPrawn** [comment] 2021-12-14 03:23
confirmed fix by reinstalling addon on FF 95.0

**Comment by magf** [comment] 2021-12-14 04:19
Just force Check for Updates.
It works!

**Comment by Sneethe** [comment] 2021-12-14 04:23
Reinstalling fixed on FF 93

**Comment by ambaca** [comment] 2021-12-14 04:24
> Just force Check for Updates. It works!

This, run addon update manually

**Comment by spamsgood** [comment] 2021-12-14 05:00
Confirmed that the taper monkey script is still doing the NaN error on safari Version 15.2 (17612.3.6.1.6)

**Comment by mteverst** [comment] 2021-12-14 05:33
I also use the user script version for chrome and Tampermonkey. 
Dislikes are reported as NAN.

**Comment by AverageHelper** [comment] 2021-12-14 06:13
Reinstalling the plugin fixed it for me. Not sure why tho...

**Comment by foobarjimmy** [comment] 2021-12-14 06:36
NaN on firefox dev edition.Addon manager-check updates fixed the problem.

**Comment by trinaldi** [comment] 2021-12-14 06:53
Can confirm.  `Firefox Nightly 97.0a1 (2021-12-13) (64-bit)`.

Simple "Check  for Update" worked.

**Comment by BrightsydeJacobDev** [comment] 2021-12-14 09:38
Same here, YouTube API for dislikes was officially shut down, the same on Hadzy was also affected aswell.

**Comment by Lucretia** [comment] 2021-12-14 11:07
I've just seen this on https://youtu.be/DRkfqiF46MQ

**Comment by moneroexamples** [comment] 2021-12-14 11:29
It was same on Android, FF Nightly 97. Reinstall of the extension fixed the issue and counting seems to be working.

**Comment by adrianjagielak** [comment] 2021-12-14 11:31
NaN instead dislikes count with Userscript on Safari 15.2 macOS Monterey 12.1

**Comment by ShadowJonathan** [comment] 2021-12-14 11:34
Same on brave.

Curiously, it shows an actual number of dislikes on some videos before quickly switching to the `NaN`

**Comment by levihb** [comment] 2021-12-14 11:55
I didn't have to reinstall, simply disabling and re-enabling the add-on fixed it. Firefox 94.0.2, Linux

**Comment by GregoryCavallera** [comment] 2021-12-14 14:14
Just had this issue on FF95, re-installing the extension as other users suggested in this thread fixed the issue for me so far.

**Comment by Shellyoung** [comment] 2021-12-14 14:33
Тоже самое
![awpfe09JII](https://user-images.githubusercontent.com/40469927/146018058-2ae9756d-2d58-425d-ac8d-747b269709d4.gif)

**Comment by Pokemo761** [comment] 2021-12-14 15:45
I having the same issue just like all you 
![cxc](https://user-images.githubusercontent.com/53906882/146031128-0a538ca7-ddec-42a4-9e37-57e0539899d5.JPG)

**Comment by Pokemo761** [comment] 2021-12-14 15:46
The NaN thing is appearing on the dislike button.

**Comment by Pokemo761** [comment] 2021-12-14 15:47
![dfdf](https://user-images.githubusercontent.com/53906882/146031435-37b5f6c4-a64a-44fe-bf93-4426894c6e04.JPG)

**Comment by Pokemo761** [comment] 2021-12-14 15:50
This problem is happing on firefox

**Comment by MaxCloud123** [comment] 2021-12-14 17:27
> Just force Check for Updates. It works!

That worked for me too in Firefox 95.0 (64-bit) on Windows 10

**Comment by Plaque-fcc** [comment] 2021-12-14 17:37
Moreover, after the update I can see the number of dislikes even where they were disabled by the author.

**Comment by Procyon-b** [comment] 2021-12-14 22:13
When will the userscript be updated? The current version is still 3 days old (dec 11).

**Comment by momala454** [comment] 2021-12-14 22:46
fix for userscript, remove those lines 
```javascript
  if (isMobile) {
    GM.xmlHttpRequest({
      method: "GET",
      url: `https://www.youtube.com/watch?v=${getVideoId()}`,
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.3674",
      },
      onload: (response) => {
        let result = getDislikesFromYoutubeResponse(response.responseText);
        if (result) {
          cLog("response from youtube:");
          cLog(JSON.stringify(result));
          if ("likes" in result && "dislikes" in result) {
            const formattedDislike = numberFormat(result.dislikes);
            setDislikes(formattedDislike);
            likesvalue = result.likes
            dislikesvalue = result.dislikes
            createRateBar(result.likes, result.dislikes);
            statsSet = true;
          }
        }
      },
    });
  } else {
    fetch(`https://www.youtube.com/watch?v=${getVideoId()}`).then((response) => {
      response.text().then((text) => {
        let result = getDislikesFromYoutubeResponse(text);
        if (result) {
          cLog("response from youtube:");
          cLog(JSON.stringify(result));
          if ("likes" in result && "dislikes" in result) {
            const formattedDislike = numberFormat(result.dislikes);
            setDislikes(formattedDislike);
            likesvalue = result.likes;
            dislikesvalue = result.dislikes;
            createRateBar(result.likes, result.dislikes);
            statsSet = true;
          }
        }
      });
    });
  }
```

**Comment by Procyon-b** [comment] 2021-12-14 22:49
@momala454 thanks

**Comment by alexmehta** [comment] 2021-12-15 06:29
forced update fixed it for me

**Comment by Anarios** [comment] 2021-12-15 06:52
Update solves the issue, closing this now

**Closed by Anarios** 2021-12-15 06:52 UTC
Labels: bug
