### ISSUE TITLE
extension showing all youtube video's dislikes as "0"

### ISSUE THREAD

**Issue by Spherey** [Anarios/return-youtube-dislike#661] opened 2022-06-27 00:43 UTC
earlier i noticed that one of the youtube videos i was watching, which had 74k likes, had the dislike value of 0, which i thought was interesting, and i didn't think much of it at first
until later, when i noticed that another video, which had 246k likes, had the dislike value of 0 as well, which made me realize that something was off
so i checked some other youtube videos and noticed that all of them had the dislike value as 0, even after refreshing the page, which means likely this is an issue with the extension
browser: opera
browser version: 87.0.4390.45
extension
extension version: v3.0.0.2
video link where the problem occurs: all
how to reproduce: go onto any youtube video

**Comment by fl-wer** [comment] 2022-06-27 00:44
duplicate of #660

**Comment by Bijoubleu** [comment] 2022-06-27 01:11
yes i've noticed that myself and I couldn't believe nobody noticed. Old video's dislikes still work but recent videos don't work anymore.

**Comment by xenago** [comment] 2022-06-27 02:40
Seconding this, it's broken

**Comment by Anarios** [comment] 2022-06-27 08:03
Fixed, sorry about that.

**Closed by Anarios** 2022-06-27 08:03 UTC
