### ISSUE TITLE
Question about a video which disabled display count of like and dislike

### ISSUE THREAD

**Issue by rk0cc** [Anarios/return-youtube-dislike#176] opened 2021-12-04 02:47 UTC
I found that this plugin still showing dislike count for a video which disabled showing viewer like and dislike count.

![Screenshot 2021-12-04 103458](https://user-images.githubusercontent.com/70585816/144694025-4a603ab0-c085-4a63-89a3-fcc6a5906557.png)
Just like this screenshot that I set this video to hide out **all like and dislike count**, when it saved and go to the video in YouTube, the dislike count still showing properly but hidden for like:
![Screenshot 2021-12-04 103549](https://user-images.githubusercontent.com/70585816/144694094-8617cf66-302c-406e-97d5-162a3f355d69.png)

I don't know is it is as a bug or a feature of plugin, but it is non-sense for keep displaying dislike count that the uploader originally hide both like and dislike count since this feature rolled out before forcing hide dislike count policy.

**Comment by Nightcaat** [comment] 2021-12-04 19:55
Duplicate of #47

**Closed** 2022-04-22 23:21 UTC
