### ISSUE TITLE
Question: API source code?

### ISSUE THREAD

**Issue by Paulmski** [Anarios/return-youtube-dislike#146] opened 2021-12-02 01:51 UTC
This may be the wrong place for this question, but I'm not sure how else to get an answer. I apologize in advance if this is not the right use of the issues section.

Where is the youtube-dislike API source code? Is it open source and can it be contributed to? If anyone can point me in the right direction I would love to assist with the backend if possible.

**Comment by SuperZing** [comment] 2021-12-02 02:26
You can go to their website and click on the discord link and then go to #i-want-to-help

**Comment by lncndev** [comment] 2021-12-02 03:00
Duplicate of #45 and #51
Maintainer seems to be denying all requests for the backend source for reasons we don't know. I was thinking about just rewriting the backend in Crystal, but would need a JS dev to help out with the extension part.

**Comment by Paulmski** [comment] 2021-12-02 12:48
Thanks for pointing me in the right direction, sorry for the duplicate.

**Closed** 2021-12-02 12:48 UTC
