### ISSUE TITLE
(Feature Request): Option for creators to submit their like/dislike ratio directly from youtube studio

### ISSUE THREAD

**Issue by lmssieh** [Anarios/return-youtube-dislike#332] opened 2021-12-16 20:06 UTC
### Extension or Userscript?

Both

### Request or suggest a new feature!

I'm sure creators who are against youtube removing dislikes wouldn't mind sharing their stats with everyone assuming there is a secure way to do it that doesn't risk their account.

### Ways to implement this!

honestly, I have no idea.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by SpaceSaver** [comment] 2021-12-16 23:05
To extend on that, there could be an option in the extension to authenticate your creator account with YouTube Studio and then the extension would scrape dislike counts and add it to the already existent database.

**Comment by ScamCast** [comment] 2021-12-17 05:55
https://github.com/Anarios/return-youtube-dislike/issues/329

**Comment by aidanhasaknife** [comment] 2021-12-17 07:47
duplicate of #84—shame on you, mx. @lmssieh! (only kidding :)

**Closed** 2021-12-17 18:17 UTC
Labels: enhancement
