### ISSUE TITLE
Dislikes are no longer showing

### ISSUE THREAD

**Issue by Raj2032** [Anarios/return-youtube-dislike#951] opened 2023-10-13 22:04 UTC
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Brave

### Browser Version

Version 1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.10

### Video link where you see the problem

https://www.youtube.com/watch?v=Juhth74rEDU

### What happened?

ANy YouTube videos you try and view e.g:

![image](https://github.com/Anarios/return-youtube-dislike/assets/29293830/85f9c232-d410-4cc5-94d2-7fff2d6a1e59)

Doesn't show the dislike at all.

Not too sure if this is an issue on my end or happening to others as well?

### How to reproduce/recreate?

Go to any YouTube video

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by tazlsucks** [comment] 2023-10-13 22:09
Duplicate of [#944](https://github.com/Anarios/return-youtube-dislike/issues/944). Please join the discord server for more information

**Comment by Anarios** [comment] 2023-10-14 11:07
Closing as duplicate. Fix is out in chrome store.

**Closed by Anarios** 2023-10-14 11:07 UTC
Labels: bug
