### ISSUE TITLE
(Bug): Update page opens frequently when starting the browser

### ISSUE THREAD

**Issue by sp96296** [Anarios/return-youtube-dislike#576] opened 2022-04-30 04:44 UTC
### Browser

Google Chrome

### Browser Version

103.0.5033.0

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.1

### Video link where you see the problem

N/A

### What happened?

Oftentimes after opening the browser, the update page is opened as a new tab. I think this has been going on since 3.0.0.0 launched, but not sure. Included below is the update page in question, the URL is the chrome-extension:// URL.

![image](https://user-images.githubusercontent.com/36968514/166091343-4142c3e4-21e6-491f-9295-0c1ca0c88642.png)

### How to reproduce/recreate?

1. Open Chrome
2. New tab w/ update page is automatically opened, even if seen before

**Comment by Unnoen** [comment] 2022-04-30 06:47
Yeah, I can confirm this is happening for me too. It has been since the 3.0.0.1 update released.

**Browser:** Brave (Chromium Based)
**Browser version:** Version 1.39.84 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
**Extension or Userscript:** Extension
**Extension version:** 3.0.0.1

I've noticed it only seems to re-open after first turning on my computer for the day.
Closing/reopening the browser (or restarting PC) doesn't seem to make it appear once it already has for the day.
Not sure what the connection is, maybe a session token/cookie expiring? I don't know the codebase so this is just a guess.

**Comment by Anarios** [comment] 2022-04-30 08:05
Very strange, 3.0.0.1 was supposed to fix it. Are you sure that it happened after extension was updated to 3.0.0.1, not before?

**Comment by Unnoen** [comment] 2022-04-30 08:28
Ah, it would have been 3.0 that it started then, however it has still opened the page since 3.0.0.1 has released.
It might be that the extension hasn't updated to 3.0.0.1 until very recently, so I'll keep an eye on it and see if it continues.

**Comment by Anarios** [comment] 2022-04-30 08:35
Thanks! Yes, that's my guess as well - I hope that it shouldn't happen in 3.0.0.1 anymore.

**Comment by sp96296** [comment] 2022-05-01 04:08
> Very strange, 3.0.0.1 was supposed to fix it. Are you sure that it happened after extension was updated to 3.0.0.1, not before?

It still seems to be happening to me, just happened now actually

**Comment by sp96296** [comment] 2022-05-02 01:49
> Can you try removing the extension from your account and re-installing? It should pop up once more, but that should be it. Your storage variables may be messed up

Just tried that, and it seems to have worked. I did not experience it aside from the initial update page post-installation, even after device reboot. I think I will close, but maybe this could be added to the FAQ in case other's also get the issue?

**Comment by sp96296** [comment] 2022-05-03 05:54
The page opened again
![image](https://user-images.githubusercontent.com/36968514/166409911-27cf1d9e-dcfb-42e2-bd18-80de5368190a.png)

**Comment by sp96296** [comment] 2022-05-03 15:43
> @sp96296 
> A couple of questions to you: Does your Chrome update often? (Is it Canary?) Besides, do you have a good and constant Internet connection?

It's canary, and internet is constant

**Comment by sy-b** [comment] 2022-05-04 00:38
> It's canary

Why is the storage bugging ?!?
Is it normal for canary?

> @sy-b any ideas why the current implementation is still this buggy?

Let's try `chrome.storage.`**`local`**. Maybe there's something fishy with **`sync`**.

**Comment by sy-b** [comment] 2022-05-04 00:50
from: https://stackoverflow.com/questions/13292744/why-isnt-localstorage-persisting-in-chrome

```
Summary seems to be that that you must attempt a read of the key in order to persist it.
```

**Comment by sy-b** [comment] 2022-05-04 11:57
👍

<br>

---

<br>

> as soon as I get some free time.

Yeah, kinda same here. Still trying to find it.

<br>

---

<br>

> Me: Look Mom! No hands!
> Mom: Laugh as you can now, until you fall and break your teeth, which you will.

My sense of humor ~~isn't~~ wasn't so bad in general but I don't understand how is this related & if it was meant to be humorous in the first place.

**Comment by Anarios** [comment] 2022-05-17 15:40
3.0.0.2 is out, please close the issue if it's fixed with this update. Or comment if it still repeats.

**Closed** 2022-05-23 05:35 UTC
Labels: bug
