### ISSUE TITLE
(Bug): Doesn't work on m.youtube.com

### ISSUE THREAD

**Issue by reconman** [Anarios/return-youtube-dislike#143] opened 2021-12-01 23:08 UTC
### Browser

Google Chrome

### Browser Version

96.0.4664.45

### Extension or Userscript?

Extension

### Extension/Userscript Version

0.0.0.9

### Video link where you see the problem

https://m.youtube.com/watch?v=YbJOTdZBX1g

### What happened?

If you go the URL and disable redirects by pretending to be a mobile client, the Dislike button is not replaced by a Dislike count as shown here

![](https://user-images.githubusercontent.com/74945202/143982211-4c7e6f56-ba76-4a78-8613-129d5d46a2ee.jpg)

This is part of #68, but other browsers on Android also support Userscripts and experience the same issue. I reproduced it on Firefox Nightly (Android) and Chrome (Desktop).

**Comment by rdev** [comment] 2021-12-02 04:07
Fixed in https://github.com/Anarios/return-youtube-dislike/commit/395fd15dfa58a9ceb937d158daac780b2fd8db41 but only on Safari

**Comment by vehosah** [comment] 2021-12-03 13:09
> Fixed in [395fd15](https://github.com/Anarios/return-youtube-dislike/commit/395fd15dfa58a9ceb937d158daac780b2fd8db41) but only on Safari

The problem is that he doesn't use safari

**Closed** 2021-12-12 19:18 UTC
Labels: bug
