### ISSUE TITLE
YouTube New UI Problems

### ISSUE THREAD

**Issue by MerBudd** [Anarios/return-youtube-dislike#801] opened 2022-11-01 12:46 UTC
### Browser

Orion

### Browser Version

0.99.120.1-beta

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.6

### Video link where you see the problem

Any video

### What happened?

_(About my browser, Orion is basically Apple's Safari, with support for Chrome and Firefox Extensions. I'm using the Chrome version of the extension. The issue isn't only with Orion though, I also tried with Edge and Chrome and both give the same results)_

1) "Reformat like numbers" doesn't work. Dislikes do reformat, but likes don't.
<img width="216" alt="image" src="https://user-images.githubusercontent.com/82082386/199232116-bf8b485d-817b-44b2-b17e-de5d429937dd.png">

2) Thumb buttons don't get recolored.

3) The ratio bar isn't aligned with the buttons properly.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/82082386/199232359-df8f5866-d81b-452a-a447-0a274ed0470e.png">

4) The dislike number is positioned too close to the thumbs down button (Compare with the like number)
<img width="161" alt="image" src="https://user-images.githubusercontent.com/82082386/199232680-96f431c4-33e0-4395-b01a-b44af3f9eb91.png">

Expected Result:
The extension adapts to the new UI and doesn't have problems.

### How to reproduce/recreate?

For issue 1 and 2: In the extension settings, turn on "Reformat like numbers" and choose any format. Toggle "Colorize thumbs" on as well.
Issue 3 and 4 don't require any configuration to be made to the settings.

Step 1) Go to any YouTube Video

Step 2) The issues should be visible.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by ryleu** [comment] 2022-11-01 17:21
![image](https://user-images.githubusercontent.com/69326171/199296515-8f72596c-6be2-489e-9e3c-24ec4ccbc975.png)
looks like this for me

**Comment by ryleu** [comment] 2022-11-01 17:34
![image](https://user-images.githubusercontent.com/69326171/199299945-649ab404-08de-4bb0-9e57-b139846ec3dc.png)
this is on a video from a larger channel with an older video

**Comment by YassineGherbi** [comment] 2022-11-01 22:10
What does "Thumb buttons don't get recolored." mean?

**Comment by MerBudd** [comment] 2022-11-02 06:44
> What does "Thumb buttons don't get recolored." mean?

The thumb buttons are these (👍 👎)
And there's a setting to recolor them (make 👍 be green and 👎 be red) but that setting doesn't work with the new UI

**Comment by sophienix** [comment] 2022-11-02 08:52
im having the same issue its cause youtube changed the gui load out so the elements are different most likely

**Comment by DemitrixQ** [comment] 2022-11-02 18:21
![изображение](https://user-images.githubusercontent.com/25634803/199570779-be1051cc-dee4-42cc-ae21-a6fbd5878f14.png)
When you switch on the extension of the disliking display

**Comment by Almashina** [comment] 2022-11-05 08:43
Подтверждаю, на мозилле при использовании расширения съезжает разметка - после обновления дизайна ютубом.
![2022-11-05_134147](https://user-images.githubusercontent.com/54445863/200111424-3efb4889-600d-4d01-914b-61e6b97b78a6.png)

**Comment by nsde** [comment] 2022-11-09 14:24
![image](https://user-images.githubusercontent.com/67185896/200855411-694ee7b3-0d1f-4b56-8dca-0dc3018c01f5.png)

**Comment by aqtsalt** [comment] 2022-11-13 19:42
it is not showing for me.
![image](https://user-images.githubusercontent.com/104331720/201540986-ac124b2a-80cc-41a8-983e-c7abe977ead4.png)

**Comment by ErykDarnowski** [comment] 2022-11-14 00:19
Hey, I've worked on a similar issue regarding the bar (in [this](https://github.com/Anarios/return-youtube-dislike/pull/771) PR)!
Let me know if the issue still persists.

**Comment by ErykDarnowski** [comment] 2022-11-15 23:41
Hey, there's a proposed solution for the dislike button's text margin issue by @Ansh4011 [here](https://github.com/Anarios/return-youtube-dislike/issues/809#issuecomment-1315579014)!

**Comment by ronny941** [comment] 2022-11-21 16:51
with this new update v3.0.0.7 the extension doesn't work it's not showing the dislikes and the likes are bugged
it appears "disabled by the owner" instead of the number of likes in all the videos
please fix it

**Comment by ErykDarnowski** [comment] 2022-11-22 15:54
@ronny941 would you mind sharing URLs of the videos you're having issues with?

In my usage I only saw the "disabled by the owner" message a couple times!

**Comment by ErykDarnowski** [comment] 2022-11-23 00:03
Hey @ronny941 I've tested this on the Chrome Web Store version of the extension (`3.0.0.7`) on Brave (`1.45.127 Chromium: 107.0.5304.110`) and Windows (`10 Pro - 1909`) and I **can't** replicate this issue.

Please specify what software you're running and give examples of videos on which the issue is present.

**Comment by ronny941** [comment] 2022-11-23 00:14
mozilla firefox v107.0
OS: Windows 10 Pro 22H2

**Comment by ronny941** [comment] 2022-11-23 00:17
![Cattura](https://user-images.githubusercontent.com/32131958/203446533-2acd4515-c157-40b2-9ac2-e483891b906f.JPG)

**Comment by ronny941** [comment] 2022-11-23 00:19
on firefox the bug is never fixed

**Comment by ronny941** [comment] 2022-11-23 18:46
it say "disabled by owner" and the dislikes is not showing
or 0 like and the dislikes it not showing
when i disabled the extension the likes of all videos it showed correctly

**Comment by ronny941** [comment] 2022-11-23 22:14
> Hey @ronny941 I've tested this on the Chrome Web Store version of the extension (`3.0.0.7`) on Brave (`1.45.127 Chromium: 107.0.5304.110`) and Windows (`10 Pro - 1909`) and I **can't** replicate this issue.
> 
> Please specify what software you're running and give examples of videos on which the issue is present.

the problem is only on firefox v107.0 
as you can see it the extension doesn't work
on chrome edge and brave it works but on firefox with the update v3.0.0.7 and the script v3.1.0 is not working

**Comment by ErykDarnowski** [comment] 2022-11-23 23:15
@ronny941 I've tested this on Firefox (`107.0`) with the extension from the Firefox ADD-ONS store (`v3.0.0.7`). I even tried switching my system's language to italian but I still couldn't replicate the problem.

Could you try replicating this issue on another computer?

**Comment by ronny941** [comment] 2022-11-23 23:25
> @ronny941 I've tested this on Firefox (`107.0`) with the extension from the Firefox ADD-ONS store (`v3.0.0.7`). I even tried switching my system's language to italian but I still couldn't replicate the problem.
> 
> Could you try replicating this issue on another computer?

i don't have any another pc for verify this issue
but i don't understand why doesn't work

**Comment by ErykDarnowski** [comment] 2022-11-23 23:26
Well me neither. If I can't replicate the issue I can't fix it.

**Comment by ronny941** [comment] 2022-11-23 23:36
> Well me neither. If I can't replicate the issue I can't fix it.

in every video it gives me this
https://user-images.githubusercontent.com/38260267/198912946-02db207e-756f-46d3-9ae6-87042d5f13a2.png
i installed the extension updated but the problem it remains
i disabled the extension and enabled but it doesn't work
i try removed and reinstalled but it doesnt' work 
i try the script with violentmonkey but it doesn't work

**Comment by ronny941** [comment] 2022-11-23 23:37
![Cattura](https://user-images.githubusercontent.com/32131958/203663862-65970eaf-de65-4b33-9929-de086b859bb7.JPG)
in every video it gives me this
i installed the extension updated but the problem it remains
i disabled the extension and enabled but it doesn't work
i try removed and reinstalled but it doesnt' work 
i try the script with violentmonkey but it doesn't work

**Comment by ronny941** [comment] 2022-11-23 23:45
it's the extension savefrom the problem
i have disabled and it worked
i hope they do a fix

**Comment by ErykDarnowski** [comment] 2022-11-24 00:04
The only thing I can suggest at this point is either trying to replicate this on a different computer or if that's not possible, doing so in a virtual machine.

Like I said. If I can't replicate the issue, I can't fix it.

**Comment by ronny941** [comment] 2022-11-24 00:11
> The only thing I can suggest at this point is either trying to replicate this on a different computer or if that's not possible, doing so in a virtual machine.
> 
> Like I said. If I can't replicate the issue, I can't fix it.

the problem is the extension savefrom net helper i
i have disabled and now the extension is working fine
i hope they updated the savefrom net extension for firefox to fix the bug

**Comment by ErykDarnowski** [comment] 2022-11-24 00:14
Ohh, ok. I understand now. In that case [this](https://github.com/Anarios/return-youtube-dislike/issues/769) issue is also related!

I'll test this out now.

**Comment by ronny941** [comment] 2022-11-24 00:17
> Ohh, ok. My bad, I understand now. In that case [this](https://github.com/Anarios/return-youtube-dislike/issues/769) issue is also related!
> 
> I'll test this out now.

thank you for your work and your disponibility

**Comment by ErykDarnowski** [comment] 2022-11-24 00:56
I mean, It's you that figured it out in the end, so congrats!

---

I've managed to replicate the issue on my end:

![image](https://user-images.githubusercontent.com/81530705/203667205-a6767ec1-5891-43c7-a9c9-4c5fa3c0187e.png)

I'm also happy to say that the fix I proposed [here](https://github.com/Anarios/return-youtube-dislike/issues/769#issuecomment-1272626099) **does** resolve the issue but it does also mess up the order of the buttons:

![image](https://user-images.githubusercontent.com/81530705/203670865-718ded0b-95f5-4c62-a7bd-942aef6a3120.png)

---

**This fix clearly needs a bit more work and testing, but it's a good start!**

**Comment by ronny941** [comment] 2022-11-24 13:20
ok i wait the fix for now i disabled savefrom net extension

**Comment by ErykDarnowski** [comment] 2022-11-26 01:00
> > 1. "Reformat like numbers" doesn't work. Dislikes do reformat, but likes don't.
> > 2. Thumb buttons don't get recolored.
> > 3. The ratio bar isn't aligned with the buttons properly.
> > 4. The dislike number is positioned too close to the thumbs down button (Compare with the like number)
> 
> 1, 3 and 4 appear to be duplicates of #772, #733 and #776 respectively after a quick search 2 seems valid tho :)

After going over the whole issue and also noticing this ^ comment (by @Moondarker), in my opinion closing this issue and opening a new one titled "Like / dislike buttons don't get recolored" would be the best move (as that's the only distinct issue in this whole thread)!

**Comment by josiahb217** [comment] 2023-02-04 18:03
In relation to the offset and #733 mentioned here, it is still noticeable that the ratio is offset, not centered. Even in the post that @ErykDarnowski posted, the after photo shows this. I have included my own photo with lines added for clarity. Sorry, I don't post to Github and I see this as being an old topic. Couldn't figure out if there was anything more recent or if a new issue should be started.
![Offset](https://user-images.githubusercontent.com/20602251/216782384-0f558626-a361-40f9-856b-8e1c3ad86e3f.png)

**Comment by ErykDarnowski** [comment] 2023-02-04 21:19
Hey @josiahb217, thank you for noticing that!

In the comment you're referring to, I was only talking about the issue of the bar stretching and **not** it's offset (I've talked about that in [this](https://github.com/Anarios/return-youtube-dislike/issues/809#issuecomment-1324378114) and [this](https://github.com/Anarios/return-youtube-dislike/issues/809#issuecomment-1326873463) comment + I've implemented a fix in [this](https://github.com/Anarios/return-youtube-dislike/pull/835) PR draft).

Unfortunately, the issues on this repo are really messy and often report the same problem. Which of course, causes a lot of confusion and allows for situations like this to occur!

Although my PR hasn't been merged, I see that this offset isn't present anymore (at least if you clone the repo and build the extension yourself). As of now, the "store" version of the extension, still has that offset (`3.0.0.7`).

**Comment by Wolterhon** [comment] 2023-02-06 17:16
![изображение](https://user-images.githubusercontent.com/23475741/217039123-5440cbd7-70ba-4e4f-be81-afa9ffe534b3.png)
This can happen when the video's aspect ratio is close to a square's (4:3 in this case)

**Comment by ErykDarnowski** [comment] 2023-02-06 19:43
Hey @Wolterhon

I've also encountered this, but in my case it happened when I was watching youtube on my vertical monitor (when the browser window is quite small horizontally). I'm working on a fix for this [here](https://github.com/Anarios/return-youtube-dislike/pull/835).

**Comment by PickleNik** [comment] 2023-05-29 17:16
> ![изображение](https://user-images.githubusercontent.com/23475741/217039123-5440cbd7-70ba-4e4f-be81-afa9ffe534b3.png) This can happen when the video's aspect ratio is close to a square's (4:3 in this case)

this will be tracked in #924

**Comment by PickleNik** [comment] 2023-05-29 17:18
the SafeForm conflict will be tracked in #769

**Comment by PickleNik** [comment] 2023-05-29 17:19
2. recoloring will be tracked in #848

**Comment by PickleNik** [comment] 2023-05-29 17:19
1, 3 and 4 have been fixed :)

**Closed by PickleNik** 2023-05-29 17:19 UTC
Labels: bug
