### ISSUE TITLE
(Feature Request): API Source Code

### ISSUE THREAD

**Issue by dabockster** [Anarios/return-youtube-dislike#241] opened 2021-12-08 00:50 UTC
### Extension or Userscript?

Both

### Request or suggest a new feature!

Where is the source code for the API at https://returnyoutubedislikeapi.com? I want to take a look at it.

### Ways to implement this!

Upload the source code to the extension API.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by MarcosLoq** [comment] 2021-12-08 03:01
Yes, I ask the dev to take care of working and modifying the API since the extension just stopped working for me recently. Take your time to do it.

**Comment by rkdl** [comment] 2021-12-08 23:16
Where is the source code, Lebowski?
I'm not gonna use this thing until the source gets publicly available

**Comment by SirLich** [comment] 2021-12-12 20:41
Yes, I think it's really important that we have all components open-sourced. You may also consider creating a github organization which houses all repos.

**Comment by pm4rcin** [comment] 2021-12-30 11:49
Any progress? I'm still waiting for it to use the extension because there were too many spyware extensions in the past that abused users privacy and were sold to third parties...

**Comment by quentincaffeino** [comment] 2021-12-30 20:29
This is a duplicate of #45, please search issues first before creating duplicates

**Comment by quentincaffeino** [comment] 2021-12-30 20:29
This is a duplicate of #45, please search issues first before creating duplicates

**Comment by Anarios** [comment] 2022-01-02 11:08
dup of #45

**Closed by Anarios** 2022-01-02 11:08 UTC
Labels: enhancement
