### ISSUE TITLE
Not working on Chrome

### ISSUE THREAD

**Issue by Razodiac** [Anarios/return-youtube-dislike#9] opened 2021-11-18 15:10 UTC
Hi, the current version 0.0.3 is not working on chrome after installed in developer mode, but it works on Firefox. Perhaps you could check what was wrong, thanks.

**Comment by dmitry-selivanov** [comment] 2021-11-18 15:25
Checked in Chrome - all seems to be fine for me. 

Which chrome version are you using, and on which videos it doesn't work?

Could you try temporary disabling all other extensions?

For now  the extension won't display dislikes for videos where author disabled dislikes (we don't have enough data yet). 
It will be possible once there are more extension users.

**Comment by davidlinye** [comment] 2021-11-18 18:21
I tried disabling all other extensions but it did not fix the problem. I did notice on the other hand that the extension has 2 errors:
![image](https://user-images.githubusercontent.com/71036780/142473813-eeb7f4bf-52c3-4e84-8481-c4cd9f8665e8.png)
I checked the details and all permissions were given properly:
![image](https://user-images.githubusercontent.com/71036780/142473927-62c4136a-d336-48d9-ac71-f95ee3a9de96.png)
Sorry about the Dutch text lol

**Comment by dmitry-selivanov** [comment] 2021-11-18 18:54
This error is normal (it's a known issue), it doesn't normally affect how extension works. Do you see dislikes?

**Comment by davidlinye** [comment] 2021-11-18 19:04
I do not see dislikes

**Comment by Anarios** [comment] 2021-11-18 19:19
are you on mac or windows?

**Comment by davidlinye** [comment] 2021-11-18 19:38
Windows

**Comment by davidlinye** [comment] 2021-11-18 19:38
Let me know if I need to provide some sort of log

**Comment by Anarios** [comment] 2021-11-18 19:50
And you use normal chrome - not chrome brave?

**Comment by davidlinye** [comment] 2021-11-18 19:51
Yes normal chrome

**Comment by Anarios** [comment] 2021-11-18 19:52
Extremely strange, there are 500+ chrome users and they don't seem to have an issue. A new release is coming soon (hopefully 3-4 hours) - it might fix your problem. I'll write here when it's ready

**Comment by davidlinye** [comment] 2021-11-18 19:52
Okay, thanks for the quick responses

**Comment by davidlinye** [comment] 2021-11-18 21:49
Btw here's proof lol i forgot
![image](https://user-images.githubusercontent.com/71036780/142502403-df0dce5c-81d4-4191-a02b-335fbd967ffe.png)

**Comment by lukszi** [comment] 2021-11-19 09:07
I'm having the same Issue.

**Comment by Razodiac** [comment] 2021-11-21 02:45
I am on a MacBook running Chrome, it does not show any dislikes on any videos. 
<img width="506" alt="Screenshot 2021-11-20 at 21 37 21" src="https://user-images.githubusercontent.com/6238924/142747243-f1e192b5-c414-4c53-8533-7b36cb425f5a.png">

However, it shows dislikes when I only enable it in the incognito mode. I tried to disable all the other extensions but the dislikes still do not appear.

**Comment by DARKDRAGON532** [comment] 2021-11-21 14:03
> I am on a MacBook running Chrome. I have updated to 0.0.0.5 version and it still does not show any dislikes on any videos. 
> <img width="506" alt="Screenshot 2021-11-20 at 21 37 21" src="https://user-images.githubusercontent.com/6238924/142747243-f1e192b5-c414-4c53-8533-7b36cb425f5a.png">
> 
> However, it shows dislikes when I only enable it in the incognito mode. I tried to disable all the other extensions but the dislikes still do not appear. 

any errors the extension  is throwing?

**Comment by randombyte-developer** [comment] 2021-11-24 11:39
It only works for me in an Incognito tab. It doesn't throw any errors.

The problem is that `getButtons()` returns `undefined`. This makes this condition fail: https://github.com/Anarios/return-youtube-dislike/blob/1854cd827dac4f699f19068c9fa4a5ac865c5aa2/Extensions/chrome/script.js#L144

Also `isVideoLoaded()` returns `false` when the condtion is checked but maybe this is just another variation of the same problem in `getButtons()`.

**Comment by Anarios** [comment] 2021-11-24 11:41
> It only works for me in an Incognito tab. It doesn't throw any errors.
> 
> The problem is that `getButtons()` returns `undefined`. This makes this condition fail:
> 
> https://github.com/Anarios/return-youtube-dislike/blob/1854cd827dac4f699f19068c9fa4a5ac865c5aa2/Extensions/chrome/script.js#L144
> 
> Also `isVideoLoaded()` returns `false` when the condtion is checked but maybe this is just another variation of the same problem in `getButtons()`.
> 
> I am on version 0.0.0.7.

it's new youtube frontend, working on a release that fixes it.

**Comment by randombyte-developer** [comment] 2021-11-26 21:52
It is fixed for me in v0.0.0.9.

**Comment by davidlinye** [comment] 2021-11-27 11:39
Yes, same!. Thanks for fixing the bug in such a short timespan.

**Closed** 2021-11-27 15:01 UTC
