### ISSUE TITLE
not working: It stopped showing dislikes.

### ISSUE THREAD

**Issue by DavidSmolinski** [Anarios/return-youtube-dislike#907] opened 2023-05-09 06:18 UTC
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

112.0.5615.165

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.8

### Video link where you see the problem

https://www.youtube.com/watch?v=_6479QAJuz8

### What happened?

no dislike count

### How to reproduce/recreate?

I stopped seeing dislikes. I removed, then added the extension.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Dheatly23** [comment] 2023-05-09 06:25
I also just experienced this problem. Btw have you tried opening the browser console? What does it say (any error)?

Mine looks like this:
![image](https://user-images.githubusercontent.com/71598333/237011661-f42dd669-ba7a-4e62-b882-3220dca5dff1.png)

**Comment by volosovich** [comment] 2023-05-09 06:47
also has this bug
```
d.content-script.js:905 Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at addLikeDislikeEventListener (ryd.content-script.js:905:23)
    at checkForJS_Finish (ryd.content-script.js:983:7)
```
`Version 112.0.5615.137 (Official Build) (arm64)`

**Comment by kratos9394** [comment] 2023-05-09 07:18
yes it is

**Comment by WildArticunoAppeared** [comment] 2023-05-09 08:25
Oddly enough, the extension still works with YouTube Shorts. It only has no effect on regular videos.

**Comment by Seraph006** [comment] 2023-05-09 09:09
not working +1

**Comment by Alluseri** [comment] 2023-05-09 09:28
Not working with and without SeriStyle, not fixing it until this is fixed.

w/o:
<img src="https://cdn.nest.rip/uploads/0841e631-052d-44c3-9178-7de5154eae08.png">
w/:
<img src="https://cdn.nest.rip/uploads/e1f77076-38e7-4020-a46c-5ed83019fa4b.png">

**Comment by StickmanOnGitHub** [comment] 2023-05-09 09:58
im also having the same issue

**Comment by AvenCores** [comment] 2023-05-09 10:12
+1
![image](https://github.com/Anarios/return-youtube-dislike/assets/64781822/59638673-7bb3-4ae9-ad82-20d00b75feda)

**Comment by domis86** [comment] 2023-05-09 10:15
also not working for me, Firefox 112, Windows 10

**Comment by StickmanOnGitHub** [comment] 2023-05-09 10:22
thats bc the youtube ui fucked up the extension

**Comment by AngelOfParadox** [comment] 2023-05-09 10:27
always

**Comment by StickmanOnGitHub** [comment] 2023-05-09 11:07
fr

**Comment by Ashdemai** [comment] 2023-05-09 11:46
> No cause for concern - the recent YouTube UI update has disrupted the extension's functionality for some users. However, we've submitted a fix for Google's review, which should take about 24 hours. When version 3.0.0.9 is released, normal operations will resume.

Thanks for the explanation and update.

**Comment by Mouadabdelghafouraitali** [comment] 2023-05-09 12:57
The update **3.0.0.9** is live now, the issue is fixed. Thank you. (Go to **Chrome > Settings > Extensions > Update**)

**Comment by Anarios** [comment] 2023-05-09 13:04
> The update **3.0.0.9** is live now, the issue is fixed. Thank you. (Go to **Chrome > Settings > Extensions > Update**)

Hmm, not in my region yet. So some people might need to wait a bit more.
![image](https://github.com/Anarios/return-youtube-dislike/assets/3018711/f8a0d631-f59d-49db-a20d-f4c2f66cb967)

**Comment by Anarios** [comment] 2023-05-09 13:05
Lol. The UI of website still displays the old version, but 3.0.0.9 gets installed when you press on "install"

**Comment by Anarios** [comment] 2023-05-09 13:06
Closing this for now, reopen only if 3.0.0.9 doesn't work.

**Closed by Anarios** 2023-05-09 13:06 UTC
Labels: bug

**Comment by Trudeau566** [comment] 2023-05-09 13:31
3.0.0.9 still doesn't work

**Comment by sapondanaisriwan** [comment] 2023-05-09 14:37
@Anarios Can you make it work with the old description panel as well?
![msedge_uJxcgVz9dG](https://github.com/Anarios/return-youtube-dislike/assets/64634605/17a23ea9-8e69-48a1-ab40-fd31d258ab36)

**Comment by sapondanaisriwan** [comment] 2023-05-11 05:04
> It seems fixed.

It still not working for me.
P.S. YouTube have 2 descriptions.
```css
ytd-watch-metadata {
    display: none !important;
}

#meta-contents[hidden],
#info-contents[hidden] {
    display: block !important;
}
```

**Comment by BakaJzon** [comment] 2023-07-27 16:13
Firefox 115
version 3.0.0.9 not working!!
