### ISSUE TITLE
(Feature Request): 

### ISSUE THREAD

**Issue by Haxorzz** [Anarios/return-youtube-dislike#110] opened 2021-11-30 13:54 UTC
### Extension or Userscript?

Both

### Request or suggest a new feature!

If YT creators support the dislike movement, have a method for the creator's videos dislikes to be automatically logged and sent to the server for others to see.
Example: If MKBHD has this extension have a toggle to automatically gather the dislikes from his videos and send it to the server for the rest of us to see.

### Ways to implement this!

Some kind of youtube studio "integration". I don't know of other ways.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by treier57lol** [comment] 2021-11-30 15:11
Duplicate of #84

**Closed** 2021-11-30 15:25 UTC
Labels: enhancement
