### ISSUE TITLE
Dislikes does not work / cannot be seen

### ISSUE THREAD

**Issue by KiwasoVR** [Anarios/return-youtube-dislike#944] opened 2023-10-12 17:57 UTC
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

118.0.5993.71

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.10

### Video link where you see the problem

All videos

### What happened?

Today, October 12, 2023 at 7:56 p.m. (Spain Time), I realized that I don't see the number of dislikes.
In the morning it did work.

Thanks, excellent plugin.

### How to reproduce/recreate?

Watching any youtube video.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Anarios** [comment] 2023-10-12 18:00
youtube just had an update that breaks the extension for a large portion of users (some UI changes) - working on a fix, all will be good soon.

**Comment by NicoTheCinderace** [comment] 2023-10-12 19:06
> youtube just had an update that breaks the extension for a large portion of users (some UI changes) - working on a fix, all will be good soon.

GOATED

**Comment by UnderscoreAngel** [comment] 2023-10-12 19:14
i just got jumpscared to death thinking youtube just killed the dislike function entirely

**Comment by phips0** [comment] 2023-10-12 19:25
I have the same problem with firefox

**Comment by NicoTheCinderace** [comment] 2023-10-12 19:28
> I have the same problem with firefox

The developer is working on it.

**Comment by Xyndra** [comment] 2023-10-12 19:35
> youtube just had an update that breaks the extension for a large portion of users (some UI changes) - working on a fix, all will be good soon.

How long do you think it will take? A hour, a day, a week?

**Comment by Nayko93** [comment] 2023-10-12 19:42
I think you should put a little icon over the thumb down when your extension don't work because of a update
Something that tell people to not panic, t's just a update, the dislike will come back soon

**Comment by acromata** [comment] 2023-10-12 20:12
There is one, it's the exact same as the dislike button, just without the numbers

**Comment by Anarios** [comment] 2023-10-12 20:41
Fix is submitted for review for all stores.

**Comment by ENTPRESTIGIOUS** [comment] 2023-10-12 22:06
I too have the same problem

**Comment by NicoTheCinderace** [comment] 2023-10-12 22:07
> I too have the same problem

The latest fix has been submitted for review on Firefox and other browsers.

**Comment by Craig-Stoneham** [comment] 2023-10-12 23:02
I use Firefox and am having the same issue

**Comment by Craig-Stoneham** [comment] 2023-10-12 23:02
I use Firefox, and I am having the same issue.

**Comment by NicoTheCinderace** [comment] 2023-10-12 23:03
> I use Firefox, and I am having the same issue.

The latest fix has been submitted for review on Firefox and other browsers.

**Comment by ParkerGit2328** [comment] 2023-10-12 23:04
Waiting for the fix to be accepted.

**Comment by Barrosy** [comment] 2023-10-13 00:12
Ouch I'm not the only one experiencing this. I am using Opera. Gracefully awaiting changes.

**Comment by Nayko93** [comment] 2023-10-13 00:34
> There is one, it's the exact same as the dislike button, just without the numbers

No I was talking about something that clearly indicate the problem is temporary and will be solved 
Having only the dislike button without the numbers just feel like return youtube dislike is gone

**Comment by Vaansh** [comment] 2023-10-13 04:20
Same problem, on chrome. Reinstalled the extension, but it does not work.

**Comment by xducker** [comment] 2023-10-13 09:47
doesn't work on Brave, too

**Comment by NicoTheCinderace** [comment] 2023-10-13 12:11
> Same problem, on chrome. Reinstalled the extension, but it does not work.



> doesn't work on Brave, too

I've said it before, and I'll say it again: The latest fix has been submitted for review on Firefox and other browsers.

We have to wait.

**Comment by JoseErnestoOnGithub** [comment] 2023-10-13 13:47
Well, how long is it gonna take for the fix to arrive?

**Comment by FyiurAmron** [comment] 2023-10-13 15:12
> Well, how long is it gonna take for the fix to arrive?

At least until it's done. Probably not longer :D

**Comment by JoseErnestoOnGithub** [comment] 2023-10-13 15:39
OK.

**Comment by TheRealBlazeKing** [comment] 2023-10-13 16:41
> > Same problem, on chrome. Reinstalled the extension, but it does not work.
> 
> > doesn't work on Brave, too
> 
> I've said it before, and I'll say it again: The latest fix has been submitted for review on Firefox and other browsers.
> 
> We have to wait.

Or people can get the zip from releases and install the updated plugin manually like I did.

**Comment by ricardonevesmusic** [comment] 2023-10-13 16:58
Yes.
I can confirm that this thing is happening (the dislikes are gone here; I suspect YouTube changed something).

**Comment by ricardonevesmusic** [comment] 2023-10-13 17:14
> > > Same problem, on chrome. Reinstalled the extension, but it does not work.
> > 
> > 
> > > doesn't work on Brave, too
> > 
> > 
> > I've said it before, and I'll say it again: The latest fix has been submitted for review on Firefox and other browsers.
> > We have to wait.
> 
> Or people can get the zip from releases and install the updated plugin manually like I did.

Yes.
I can confirm that this thing is happening (the dislikes are gone here; I suspect YouTube changed something).

I've also tried to manually install the extension and it worked normally (it's fixed now).

I'll just wait for Google to update the extension version in the store.

If you install the extension manually, you should be good (otherwise just wait for it to be updated in the stores; most of you should wait for the store update as the developer states that you should remove the manual extension once the updated version comes to the stores; if you don't normally update things manually, you'd be better off waiting just a little bit more).

That's it.

You should be good with manual extension installation (just don't forget to remove it once Google/Mozilla updates it in the store).

**Comment by ricardonevesmusic** [comment] 2023-10-13 17:15
> > > Same problem, on chrome. Reinstalled the extension, but it does not work.
> > 
> > 
> > > doesn't work on Brave, too
> > 
> > 
> > I've said it before, and I'll say it again: The latest fix has been submitted for review on Firefox and other browsers.
> > We have to wait.
> 
> Or people can get the zip from releases and install the updated plugin manually like I did.

Yes.
I can confirm that this thing is happening (the dislikes are gone here; I suspect YouTube changed something).

I've also tried to manually install the extension and it worked normally (it's fixed now).

I'll just wait for Google to update the extension version in the store.

If you install the extension manually, you should be good (otherwise just wait for it to be updated in the stores; most of you should wait for the store update as the developer states that you should remove the manual extension once the updated version comes to the stores; if you don't normally update things manually, you'd be better off waiting just a little bit more).

That's it.

You should be good with the manual extension installation (just don't forget to remove it once Google/Mozilla updates it in the store).

**Comment by lukasfink1** [comment] 2023-10-13 20:44
> I think you should put a little icon over the thumb down when your extension don't work because of a update Something that tell people to not panic, t's just a update, the dislike will come back soon

This is not really possible I’m afraid. This plugin works by injecting the dislike count at a certain position into the DOM of Youtube. If Youtube does UI changes like here, the problem is not that the plugin isn’t able to acquire the current dislike count anymore (it still is), but rather that the DOM is now different and the plugin doesn’t know where to inject the dislike count anymore. If it wasn’t able to inject the dislike count, it likely wouldn’t be able to inject an icon either.

**Comment by FarrierTheFirst** [comment] 2023-10-13 23:23
> > Same problem, on chrome. Reinstalled the extension, but it does not work.
> 
> > doesn't work on Brave, too
> 
> I've said it before, and I'll say it again: The latest fix has been submitted for review on Firefox and other browsers.
> 
> We have to wait.

A timeframe at all would be nice instead of "we just have to wait" ... for hours? days? weeks? come on now man lmao

**Comment by lucysim9** [comment] 2023-10-13 23:37
@FarrierTheFirst what's taking so long is the web stores taking forever to review the new release

**Comment by NicoTheCinderace** [comment] 2023-10-13 23:42
> > > Same problem, on chrome. Reinstalled the extension, but it does not work.
> > 
> > 
> > > doesn't work on Brave, too
> > 
> > 
> > I've said it before, and I'll say it again: The latest fix has been submitted for review on Firefox and other browsers.
> > We have to wait.
> 
> A timeframe would be nice and good customer service instead of "we just have to wait" uh for hours? days? weeks? come on now lmao it's 2023 and y'all slacking on an extension
> 
> still not working and it's 4:30 PST 10/13/23 -- what's taking so long

As Lucysim9 states, It's the webstores taking forever to review the new release - It isn't as straightforward or as simple as it sounds. it takes **time.**

If time weren't a factor and we didn't have to rely on webstores taking forever, A new update would've been out already. Perhaps you should have some patience instead of bitching about "What's taking so long". Just saying.

**Comment by akshaybharwani** [comment] 2023-10-13 23:46
Y'all are using an Open Source Software. Nobody owes you any customer service. Don't be that [Open Source user](https://jacobtomlinson.dev/posts/2022/dont-be-that-open-source-user-dont-be-me/)

**Comment by NicoTheCinderace** [comment] 2023-10-13 23:58
> Y'll are using an Open Source Software. Nobody owes you any customer service. Don't be that [Open Source user](https://jacobtomlinson.dev/posts/2022/dont-be-that-open-source-user-dont-be-me/).

Don't worry, I had no plans of it. I just hate how people are impatient.

**Comment by akshaybharwani** [comment] 2023-10-14 00:07
> > Y'll are using an Open Source Software. Nobody owes you any customer service. Don't be that [Open Source user](https://jacobtomlinson.dev/posts/2022/dont-be-that-open-source-user-dont-be-me/).
> 
> Don't worry, I had no plans of it. I just hate how people are impatient.

You're cool. I was referring to the same people you are. I totally understand.

**Comment by ItsJayUK** [comment] 2023-10-14 01:34
> > > Same problem, on chrome. Reinstalled the extension, but it does not work.
> > 
> > 
> > > doesn't work on Brave, too
> > 
> > 
> > I've said it before, and I'll say it again: The latest fix has been submitted for review on Firefox and other browsers.
> > We have to wait.
> 
> A timeframe would be nice and good customer service instead of "we just have to wait" uh for hours? days? weeks? come on now lmao it's 2023 and y'all slacking on an extension
> 
> still not working and it's 4:30 PST 10/13/23 -- what's taking so long

It's a free an open source extension. What are you on?

**Comment by orenong** [comment] 2023-10-14 03:18
I'm sure that youtube did it intentionally

**Comment by Extravi** [comment] 2023-10-14 04:30
> I'm sure that youtube did it intentionally

why?

**Comment by Barrosy** [comment] 2023-10-14 07:46
> > > Same problem, on chrome. Reinstalled the extension, but it does not work.
> > 
> > 
> > > doesn't work on Brave, too
> > 
> > 
> > I've said it before, and I'll say it again: The latest fix has been submitted for review on Firefox and other browsers.
> > We have to wait.
> 
> Or people can get the zip from releases and install the updated plugin manually like I did.

I wonder how I can do this. Is there some guide on how to manually install stuff? I tried to search it up but all I can find is a ZIP of the repository itself and loading this on Opera will result in a Manifest file missing error.

**Comment by qawasx** [comment] 2023-10-14 09:42
Why does it take so long for Firefox to get updated? And why is firefox so ass-backwards, that i can't even install it manually???

**Comment by d-bucur** [comment] 2023-10-14 11:03
The amount of entitled twats like @FarrierTheFirst is disheartening. I suggest locking conversations like these and pinning an answer that the update is in the process of shipping. People can live two days without youtube dislikes without spamming nonsense here like on a Discord channel.

**Comment by Anarios** [comment] 2023-10-14 11:11
Chrome version is out in the store. FF still reviewing.

**Comment by NicoTheCinderace** [comment] 2023-10-14 12:13
> Why does it take so long for Firefox to get updated? And why is firefox so ass-backwards, that i can't even install it manually???

Because Firefox is as slow as a glacier when it comes to this.

**Comment by virtuallyunknown** [comment] 2023-10-14 14:26
I feel bad for any extension developers out there having to deal with Mozilla and their ancient addon review process. For those unaware, essentially what happens is when you publish an updated version of your extension on addons.mozilla.org, it goes through an automated review process which scans your code, and after a short while it gets verified and "signed" by Mozilla, making it publicly available for everyone to use.

The whole process takes under 5 minutes usually, except when your addon gets stuck in this so called "awaiting review" phase for no apparent reason whatsoever, and then you're basically screwed up big time. I have experienced this first hand and reported the issue, **that was almost 4 years ago**! Their forums are full of devs reporting the same issue, sometimes getting stuck in "awaiting review" for months.

I can only speculate what is happening here because in theory popular extensions such as this one should get priority support and manual review, but nevertheless we as consumers of this extension can all observe the end result - the devs pushed a fix/update more than 2 days ago, yet Firefox users are stuck on v3.0.0.10 unable to update. I find this to be just plain disrespectful.

**Comment by NicoTheCinderace** [comment] 2023-10-14 15:03
> I feel bad for any extension developers out there having to deal with Mozilla and their ancient addon review process. For those unaware, essentially what happens is when you publish an updated version of your extension on addons.mozilla.org, it goes through an automated review process which scans your code, and after a short while it gets verified and "signed" by Mozilla, making it publicly available for everyone to use.
> 
> The whole process takes under 5 minutes usually, except when your addon gets stuck in this so called "awaiting review" phase for no apparent reason whatsoever, and then you're basically screwed up big time. I have experienced this first hand and reported the issue, **that was almost 4 years ago**! Their forums are full of devs reporting the same issue, sometimes getting stuck in "awaiting review" for months.
> 
> I can only speculate what is happening here because in theory popular extensions such as this one should get priority support and manual review, but nevertheless we as consumers of this extension can all observe the end result - the devs pushed a fix/update more than 2 days ago, yet Firefox users are stuck on v3.0.0.10 unable to update. I find this to be just plain disrespectful.

This is outright insulting, holy shit. Someone needs to tell Mozilla to stop dragging their feet.

**Comment by virtuallyunknown** [comment] 2023-10-14 15:47
> This is outright insulting, holy shit. Someone needs to tell Mozilla to stop dragging their feet.

I cut Mozilla some slack for a lot of things, but this has been going for far too long, and at least on the surface it appears that not much is being done about it, if anything at all. Either way, don't want to go too off-topic, just wanted to provide some context of what might be the issue here since I saw some people complaining.

**Comment by nguyenle2457** [comment] 2023-10-14 18:18
Those unfortunate ones who are putting up with Firefox's draconian add-on restrictions and wanting to manually install on stable release, [follow this guide](https://gist.github.com/TheBrokenRail/c43bf0f07f4860adac2631a1bd9e4136) to allow sideloading unverfied add-ons again.
I did this on Windows by simply renaming it to omni.zip, opening it with WinRAR to make relevant edits before saving and closing to let WinRAR update the archive, then finally renaming back. The file gets replaced when Firefox updates so you'll have to do it again if you need to in the future.

**Comment by qawasx** [comment] 2023-10-14 18:55
> Those unfortunate ones who are putting up with Firefox's draconian add-on restrictions and wanting to manually install on stable release, [follow this guide](https://gist.github.com/TheBrokenRail/c43bf0f07f4860adac2631a1bd9e4136) to allow sideloading unverfied add-ons again. I did this on Windows by simply renaming it to omni.zip, opening it with WinRAR to make relevant edits before saving and closing to let WinRAR update the archive, then finally renaming back. The file gets replaced when Firefox updates so you'll have to do it again if you need to in the future.

How do i do that in windows?

**Comment by mikelam14** [comment] 2023-10-14 19:18
Confirmed fix in Chrome! Bravo!

**Comment by ner00** [comment] 2023-10-14 21:10
3.0.0.11 still not working in Firefox by Debug/Loading Temporary Extension

**Comment by akshaybharwani** [comment] 2023-10-15 00:34
I just switched to using Firefox Dev Edition. Fix works.

**Comment by SmailHammour** [comment] 2023-10-15 08:32
Can confirm that this is fixed in 3.0.0.11. Thank you so much for you hard work!

**Comment by elmobark** [comment] 2023-10-16 11:49
i can confirm it's work in chrome 118.0.5993.70 macOS

**Comment by ultrono** [comment] 2023-10-16 17:36
Confirmed version 3.0.0.11 works in FireFox Dev. Edition. Many thanks.

**Comment by tensor5g** [comment] 2023-10-17 01:50
I am on Firefox 119.0b9 with extension version 3.0.0.11 and it still does not work. Any ideas?

**Comment by NicoTheCinderace** [comment] 2023-10-17 03:07
It's working for me now.

**Comment by s-h-a-d-o-w** [comment] 2023-10-17 10:44
Looks like Youtube has changed something again. 3.0.0.11 worked for a few days, but now it doesn't anymore.

```
TypeError: getLikeButton().querySelector(...) is null
```

Like button DOM (it's not the same on all browsers - guess they're running an experiment?):
```
<div id="segmented-like-button" class="style-scope ytd-segmented-like-dislike-button-renderer">
   <ytd-toggle-button-renderer class="style-scope ytd-segmented-like-dislike-button-renderer" button-renderer="true">
      <!--css-build:shady-->
      <yt-button-shape>
         <button class="yt-spec-button-shape-next yt-spec-button-shape-next--tonal yt-spec-button-shape-next--mono yt-spec-button-shape-next--size-m yt-spec-button-shape-next--icon-leading yt-spec-button-shape-next--segmented-start" style="" aria-pressed="false" aria-label="like this video along with 13,802 other people" title="">
            <div class="yt-spec-button-shape-next__icon" aria-hidden="true">
               <yt-icon style="width: 24px; height: 24px;">
                  <yt-animated-icon class="style-scope yt-icon" animated-icon-type="LIKE">
                     <!--css-build:shady--><!--css-build:shady-->
                     <ytd-lottie-player class="style-scope yt-animated-icon">
                        <lottie-component class="lottie-component">
                           <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 270 270" width="270" height="270" style="width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px);" preserveAspectRatio="xMidYMid meet">
                              <defs>
                                 <clipPath id="__lottie_element_126">
                                    <rect width="270" height="270" x="0" y="0"></rect>
                                 </clipPath>
                                 <clipPath id="__lottie_element_128">
                                    <path d="M0,0 L120,0 L120,120 L0,120z"></path>
                                 </clipPath>
                                 <clipPath id="__lottie_element_142">
                                    <path d="M0,0 L128,0 L128,128 L0,128z"></path>
                                 </clipPath>
                              </defs>
                              <g clip-path="url(#__lottie_element_126)">
                                 <g clip-path="url(#__lottie_element_142)" style="display: none;">
                                    <g style="display: none;">
                                       <g>
                                          <path stroke-linecap="round" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path stroke-linecap="round" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path stroke-linecap="round" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path stroke-linecap="round" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path stroke-linecap="round" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path stroke-linecap="round" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                       <g>
                                          <path></path>
                                       </g>
                                    </g>
                                    <g style="display: none;">
                                       <g>
                                          <path stroke-linecap="round" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                       </g>
                                    </g>
                                 </g>
                                 <g clip-path="url(#__lottie_element_128)" style="display: block;" transform="matrix(1.0880000591278076,0,0,1.0880000591278076,69.95299530029297,67.9433822631836)" opacity="1">
                                    <g style="display: none;">
                                       <path></path>
                                       <path stroke-linecap="butt" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                    </g>
                                    <g style="display: block;" transform="matrix(1,0,0,1,60,60)" opacity="1">
                                       <path stroke-linecap="butt" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4" stroke="rgb(0,0,0)" stroke-opacity="1" stroke-width="4" d=" M25.025999069213867,-4.00600004196167 C25.025999069213867,-4.00600004196167 5.992000102996826,-3.996999979019165 5.992000102996826,-3.996999979019165 C5.992000102996826,-3.996999979019165 11.012999534606934,-22.983999252319336 11.012999534606934,-22.983999252319336 C12.230999946594238,-26.90399932861328 13,-31.94300079345703 8.994000434875488,-31.981000900268555 C7,-32 5,-32 4.021999835968018,-31.007999420166016 C4.021999835968018,-31.007999420166016 -19.993000030517578,-5.03000020980835 -19.993000030517578,-5.03000020980835 C-19.993000030517578,-5.03000020980835 -20.027999877929688,32.025001525878906 -20.027999877929688,32.025001525878906 C-20.027999877929688,32.025001525878906 20.97599983215332,31.986000061035156 20.97599983215332,31.986000061035156 C25.010000228881836,31.986000061035156 26.198999404907227,29.562000274658203 26.99799919128418,25.985000610351562 C26.99799919128418,25.985000610351562 31.972000122070312,4.026000022888184 31.972000122070312,4.026000022888184 C33,-0.6930000185966492 30.392000198364258,-4.00600004196167 25.025999069213867,-4.00600004196167z"></path>
                                    </g>
                                    <g style="display: none;">
                                       <path></path>
                                       <path stroke-linecap="butt" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4"></path>
                                    </g>
                                    <g style="display: block;" transform="matrix(1,0,0,1,60,60)" opacity="1">
                                       <path stroke-linecap="butt" stroke-linejoin="miter" fill-opacity="0" stroke-miterlimit="4" stroke="rgb(0,0,0)" stroke-opacity="1" stroke-width="4" d=" M-19.986000061035156,-4.03000020980835 C-19.986000061035156,-4.03000020980835 -36.020999908447266,-3.996999979019165 -36.020999908447266,-3.996999979019165 C-36.020999908447266,-3.996999979019165 -36.00199890136719,31.993000030517578 -36.00199890136719,31.993000030517578 C-36.00199890136719,31.993000030517578 -20.030000686645508,32.02299880981445 -20.030000686645508,32.02299880981445 C-20.030000686645508,32.02299880981445 -19.986000061035156,-4.03000020980835 -19.986000061035156,-4.03000020980835z"></path>
                                    </g>
                                 </g>
                              </g>
                           </svg>
                        </lottie-component>
                     </ytd-lottie-player>
                  </yt-animated-icon>
                  <!--css-build:shady--><!--css-build:shady-->
               </yt-icon>
            </div>
            <div class="yt-spec-button-shape-next__button-text-content">
               <yt-animated-rolling-number class="animated-rolling-number-wiz" style="height: 36px; line-height: 36px;" dir="ltr" aria-hidden="true">
                  <animated-rolling-character class="animated-rolling-character-wiz" style="margin-top: -36px;">
                     <div>&nbsp;</div>
                     <div>1</div>
                     <div>2</div>
                     <div>3</div>
                     <div>4</div>
                     <div>5</div>
                     <div>6</div>
                     <div>7</div>
                     <div>8</div>
                     <div>9</div>
                     <div>0</div>
                     <div>1</div>
                     <div>2</div>
                     <div>3</div>
                     <div>4</div>
                     <div>5</div>
                     <div>6</div>
                     <div>7</div>
                     <div>8</div>
                     <div>9</div>
                     <div>0</div>
                     <div>1</div>
                     <div>2</div>
                     <div>3</div>
                     <div>4</div>
                     <div>5</div>
                     <div>6</div>
                     <div>7</div>
                     <div>8</div>
                     <div>9</div>
                     <div>&nbsp;</div>
                  </animated-rolling-character>
                  <animated-rolling-character class="animated-rolling-character-wiz" style="margin-top: -108px;">
                     <div>&nbsp;</div>
                     <div>1</div>
                     <div>2</div>
                     <div>3</div>
                     <div>4</div>
                     <div>5</div>
                     <div>6</div>
                     <div>7</div>
                     <div>8</div>
                     <div>9</div>
                     <div>0</div>
                     <div>1</div>
                     <div>2</div>
                     <div>3</div>
                     <div>4</div>
                     <div>5</div>
                     <div>6</div>
                     <div>7</div>
                     <div>8</div>
                     <div>9</div>
                     <div>0</div>
                     <div>1</div>
                     <div>2</div>
                     <div>3</div>
                     <div>4</div>
                     <div>5</div>
                     <div>6</div>
                     <div>7</div>
                     <div>8</div>
                     <div>9</div>
                     <div>&nbsp;</div>
                  </animated-rolling-character>
                  <animated-rolling-character class="animated-rolling-character-wiz" style="margin-top: -36px;">
                     <div>&nbsp;</div>
                     <div>K</div>
                     <div>&nbsp;</div>
                  </animated-rolling-character>
               </yt-animated-rolling-number>
            </div>
            <yt-touch-feedback-shape style="border-radius: inherit;">
               <div class="yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--touch-response" aria-hidden="true">
                  <div class="yt-spec-touch-feedback-shape__stroke" style=""></div>
                  <div class="yt-spec-touch-feedback-shape__fill" style=""></div>
               </div>
            </yt-touch-feedback-shape>
         </button>
      </yt-button-shape>
      <tp-yt-paper-tooltip fit-to-visible-bounds="" offset="8" role="tooltip" tabindex="-1" style="inset: auto auto 36px 0px;">
         <!--css-build:shady-->
         <div id="tooltip" class="style-scope tp-yt-paper-tooltip hidden" style-target="tooltip">
            I like this
         </div>
      </tp-yt-paper-tooltip>
   </ytd-toggle-button-renderer>
</div>
```

**Comment by nose-gnome** [comment] 2023-10-18 13:28
Version 3.0.0.11 is working for me on Firefox as well.

**Comment by s-h-a-d-o-w** [comment] 2023-10-18 13:40
3.0.0.12 fixed [the problem I described above](https://github.com/Anarios/return-youtube-dislike/issues/944#issuecomment-1766156195). Thanks!

**Comment by vivianta213** [comment] 2023-10-18 13:48
The extension hasn't worked for me on Vivaldi browser since the YT update last week. It worked for years up to this point adding it to vivaldi from the chrome store.

**Comment by ricardonevesmusic** [comment] 2023-10-18 18:39
> 3.0.0.12 fixed [the problem I described above](https://github.com/Anarios/return-youtube-dislike/issues/944#issuecomment-1766156195). Thanks!

It's true.

It worked before, but now it stopped working.

Had to manually install the v3.0.0.12 and now everything is working again.

For now I've decided to update the extension manually until these types of things stop occurring so often.

Hope these things get solved soon and that the extension becomes "stable" again (it's a bit of a hassle for it to be happening this often).

Once these things get solved for good, I'll get back to the store version (until then I'll stick with the manual extension).

If it stops working again, don't forget to update it (otherwise, I hope the dev finds a more long-term solution).

We'll see what happens (for now, everything is working greatly).

**Comment by SigEpBlue** [comment] 2023-10-18 23:10
v3.0.0.12 is working great for me on Chromium browsers. Thanks, Anarios!

No such luck with v3.0.0.11 on Firefox though, and according to Mozilla documentation, I'd need to use Firefox ESR, Nightly, or Developer Edition in order to bypass their "extension signing" requirement, and install v3.0.0.12. 🙄

Oh well, I'll just wait for this latest version to be signed and approved.

**Comment by SaltyCucumber** [comment] 2023-10-19 13:08
Still doesn't work in chrome
Using 3.0.0.12

![image](https://github.com/Anarios/return-youtube-dislike/assets/748932/7d7c7201-579a-4040-aab0-f909ca2a6c98)

**Comment by NicoTheCinderace** [comment] 2023-10-23 21:34
It's broken again!

**Comment by ricardonevesmusic** [comment] 2023-10-23 22:51
> It's broken again!

Seems to be working just fine over here (make sure you have the latest version installed).

**Comment by Nightcaat** [comment] 2023-10-24 03:07
> Still doesn't work in chrome Using 3.0.0.12
> 
> ![image](https://user-images.githubusercontent.com/748932/276624124-7d7c7201-579a-4040-aab0-f909ca2a6c98.png)

Thanks for the report, I would suggest [creating a new issue](https://github.com/Anarios/return-youtube-dislike/issues/new/choose) for this though :)

**Comment by NicoTheCinderace** [comment] 2023-10-24 17:07
> > It's broken again!
> 
> Seems to be working just fine over here (make sure you have the latest version installed).

I have the latest version installed, and now Dislikes are showing as "Temporarily Unavailable". Once more, I suspect YouTube meddling with UI changes. For the record, I'm using 3.0.0.12 for Return YouTube Dislike, and 119.0 for  Firefox.

**Comment by proninyaroslav** [comment] 2023-10-24 17:33
@NicoTheCinderace 
I opened a separate issue: https://github.com/Anarios/return-youtube-dislike/issues/975

**Comment by Pentazer** [comment] 2023-12-04 21:54
Opera GX - LVL5 (core: 104.0.4944.85)
Chromium version:118.0.5993.118
using version v3.0.0.12

Dislikes not showing on this either as of a few days ago.

**Comment by oktav** [comment] 2023-12-07 15:11
Dislikes not showing today, was working yesterday.
I'm on firefox 120.0.1 (64-bit) and extension version 3.0.0.12

I'm seeing the following in the console:
TypeError: getLikeTextContainer() is null

**Comment by Anarios** [comment] 2023-12-14 14:10
Fixed in 3.0.0.14

**Closed by Anarios** 2023-12-14 14:10 UTC
Labels: bug

**Comment by Skyfire2008** [comment] 2024-01-29 08:59
Broken again, doesn't show the like/dislike bar and the dislike count.
Console displays this: 
![image](https://github.com/Anarios/return-youtube-dislike/assets/8277644/063a8e72-7932-4116-aa1e-3ea59706f840)

Browser: Chrome v120.0.6099.217
Extension v3.0.0.14

**Comment by Anarios** [comment] 2024-01-29 09:08
Upgrading database cluster, some downtime is expected, all should be back in ~15 minutes.

**Comment by NicoTheCinderace** [comment] 2024-01-29 22:56
> Upgrading database cluster, some downtime is expected, all should be back in ~15 minutes.

It's been more than 15 minutes...

**Comment by PressStart2GameOver** [comment] 2024-01-31 19:39
Status 500 again (Revanced Extended v19.03.35)
![Screenshot_20240131-113755_ReVanced Extended](https://github.com/Anarios/return-youtube-dislike/assets/145813883/57574f6e-845b-45eb-9588-1afc7adc0634)

**Comment by behrad2k** [comment] 2024-06-08 09:19
not working for me either

**Comment by loadstring1** [comment] 2024-06-12 17:14
userscript: v3.1.5 - dislike doesn't work and it can't be seen.
browser: firefox

extension on firefox seems to be outdated please update extension and userscript

**Comment by qawasx** [comment] 2024-06-12 17:50
extension VERY outdated on firefox, userscript is 2 months old. please update

**Comment by allanlaal** [comment] 2025-04-18 09:48
seems to be broken again. all channels show "DISABLED BY OWNER"

**Comment by roymasad** [comment] 2025-04-20 05:22
same, it stopped working on chrome and brave since a couple of days ago
