### ISSUE TITLE
(Feature Request): 

### ISSUE THREAD

**Issue by josephcrosmanplays532** [Anarios/return-youtube-dislike#409] opened 2022-01-08 04:39 UTC
### Extension or Userscript?

Both

### Request or suggest a new feature!

I heard that there is a new feature on youtube called youtube shorts. they created links in each of them starting with the /shorts/ path. the issue is, the dislike count is not showing up. so i suggest that you create a feature where the dislike count is visable on the shorts as well. not just the /watch path. just try to keep it simple. if you can't, i'll try my best to work good on this.

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by cyrildtm** [comment] 2022-01-08 15:56
OP requesting shorts support. Possible duplicate of #382

**Closed** 2022-01-08 18:10 UTC
Labels: enhancement
