### ISSUE TITLE
Return Youtube Dislike uses the share button instead of the dislike button

### ISSUE THREAD

**Issue by Reinhard50** [Anarios/return-youtube-dislike#977] opened 2023-10-29 02:37 UTC
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Ungoogled Chromium

### Browser Version

118.0.5993.88

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.12

### Video link where you see the problem

Every video

### What happened?

The extension will instead replace the "Share" text to the dislike value, in the share button.

![bug](https://github.com/Anarios/return-youtube-dislike/assets/82814388/c8e1b98b-6056-40bf-9aba-35feb9ec8905)

### How to reproduce/recreate?

It's specific to this browser, from what I know.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by tea5122** [comment] 2023-10-29 12:08
Same thing on FireFox!

**Comment by AHoroszkiewicz** [comment] 2023-10-31 10:15
Same on OperaGX

**Comment by qiura122** [comment] 2023-11-01 11:21
same on my 2nd brave browser, but my 1st profile it's fine

**Comment by Bravo555** [comment] 2023-11-04 16:24
Looks like a duplicate of #948

**Comment by Bravo555** [comment] 2023-11-04 17:47
I created a fix, If you want to test it, you can download the extension for your browser from here: https://github.com/Bravo555/return-youtube-dislike/releases/tag/v3.0.0.13r1.

You'll need to sideload the extension into the browser.

Alternatively, if you don't want to load unverified zip files, you can clone my [branch with the fix](https://github.com/Bravo555/return-youtube-dislike/tree/fix/948/dislike-count-on-share-button) and build it yourself by following the [CONTRIBUTING.md](https://github.com/Anarios/return-youtube-dislike/blob/main/CONTRIBUTING.md) guide.

**Comment by Nightcaat** [comment] 2023-11-15 23:16
Duplicate of #948, fixed in https://github.com/Anarios/return-youtube-dislike/commit/adbd0fd947ccd2a394d7c2e07cc3f94ccbfe3375

**Closed by Nightcaat** 2023-11-15 23:16 UTC
Labels: bug
