### ISSUE TITLE
Thumbs up isn't appearing

### ISSUE THREAD

**Issue by MesaBlack** [Anarios/return-youtube-dislike#1054] opened 2024-06-04 02:49 UTC
### Have you tried to find similar issues (open or recently closed)?

- [X] Yes, this issue is not a duplicate

### Browser

Google Chrome

### Browser Version

Chrome v124

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 3.0.0.16

### Video link where you see the problem

https://www.youtube.com/watch?v=sLxSQw2QKVk

### What happened?

![image](https://github.com/Anarios/return-youtube-dislike/assets/132141735/b8c91061-4941-4ba5-b5f1-cd8546fb997f)

I can't see the thumbs up for liking.

### How to reproduce/recreate?

run the versions of the browser and extension i have, run it on that video

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by susegg** [comment] 2024-06-04 03:14
**`+1`** - I'm just adding that it also occurs in Firefox `v126.0.1` in case other users here see this - Extension there on `v3.0.0.14`

**Comment by malexosh** [comment] 2024-06-04 04:04
The like button is not visible for all users (without the ext installed). Likely a site change in-progess.

**Comment by wanderingmagus** [comment] 2024-06-04 07:31
> **`+1`** - I'm just adding that it also occurs in Firefox `v126.0.1` in case other users here see this - Extension there on `v3.0.0.14`

Confirming this behavior, also Firefox 126.0.1 (64-bit) and extension version  v3.0.0.14 .

**Comment by AvenCores** [comment] 2024-06-04 11:21
+1 
![image](https://github.com/Anarios/return-youtube-dislike/assets/64781822/ffee1283-f3a0-4fab-b9a2-17f15d0d6993)
![image](https://github.com/Anarios/return-youtube-dislike/assets/64781822/8c643b5b-2648-4d90-9c80-8df49ba51b43)
![image](https://github.com/Anarios/return-youtube-dislike/assets/64781822/2fa15be6-e092-4b47-959e-9ef48f9c9d53)
![image](https://github.com/Anarios/return-youtube-dislike/assets/64781822/5b1f375a-c0f8-4ad7-96b2-f161d8097ad0)

**Comment by MesaBlack** [comment] 2024-06-04 11:29
![image](https://github.com/Anarios/return-youtube-dislike/assets/132141735/0850f12f-c108-4417-88ca-53323a5e8e0f)

**Comment by zpatten** [comment] 2024-06-04 22:29
Confirmed on Chrome Version 125.0.6422.141 (Official Build) (64-bit), plugin v3.0.0.16

**Comment by joerg-nafcom** [comment] 2024-06-04 23:47
Confirmed on 
Vivaldi | 6.7.3329.39 (Stable channel) (64-bit) plugin v3.0.0.16
-

**Comment by MesaBlack** [comment] 2024-06-05 01:21
yayyyy
![image](https://github.com/Anarios/return-youtube-dislike/assets/132141735/7c27a1a1-48b9-452f-96d0-1b96dcffa520)

**Comment by joerg-nafcom** [comment] 2024-06-05 01:25
> yayyyy ![image](https://private-user-images.githubusercontent.com/132141735/336653098-7c27a1a1-48b9-452f-96d0-1b96dcffa520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTA5NDMsIm5iZiI6MTcxNzU1MDY0MywicGF0aCI6Ii8xMzIxNDE3MzUvMzM2NjUzMDk4LTdjMjdhMWExLTQ4YjktNDUyZi05NmQwLTFiOTZkY2ZmYTUyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwMTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTIxMDUxZTM5MzhiZGI4YzE2MjUzMDRiMzdhMWM5N2U4ZWYzNThlZjU4NGZjM2MwNTFhMjhhZjdkMTFiMjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K90kwaKrjRDBWWDpU35LTfWnq7br8xSNqZ7ddA7fwvA)

can confirm, it's back for me in Vivaldi, as well

**Comment by wanderingmagus** [comment] 2024-06-05 06:28
Confirm it works again on Firefox 126.0.1 (64-bit) and extension version v3.0.0.14 !

**Comment by AvenCores** [comment] 2024-06-05 09:27
It works again on Yandex browser 24.4.4.1168
![image](https://github.com/Anarios/return-youtube-dislike/assets/64781822/3412f375-f669-4c9e-a81c-001a0e62ab68)

**Comment by mamchyts** [comment] 2024-06-05 17:44
https://www.theverge.com/2024/6/4/24171475/youtube-like-button-thumbs-up-disappearing-bug

**Comment by Nightcaat** [comment] 2024-06-12 01:37
Closing as invalid due to being a YouTube issue, though this has been resolved anyway

**Closed by Nightcaat** 2024-06-12 01:37 UTC
Labels: bug

**Comment by MesaBlack** [comment] 2024-06-12 02:00
gtfoh thumbdowner

**Comment by MesaBlack** [comment] 2024-06-12 02:02
@krystian3w. Brush your teeth and go to bed, silly boy.
